// Code generated by hertz generator.

package main

import (
	"log"
	"time"

	apichat "StreamCore/api/chat"
	"StreamCore/api/router"
	"StreamCore/api/rpc"
	"StreamCore/config"
	"StreamCore/internal/pkg/base"
	"StreamCore/internal/pkg/base/infra"
	"StreamCore/internal/pkg/constants"
	"StreamCore/pkg/util"
	"context"

	sentinel "github.com/alibaba/sentinel-golang/api"
	"github.com/alibaba/sentinel-golang/core/flow"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	"github.com/hertz-contrib/cors"
	"github.com/hertz-contrib/obs-opentelemetry/tracing"
	hertzSentinel "github.com/hertz-contrib/opensergo/sentinel/adapter"
)

var (
	serviceName = constants.ApiServiceName
	logPrefix   = "[api]"
)

func init() {
	config.Init(serviceName)
	rpc.Init()

	rdb, err := infra.InitRedis()
	if err != nil {
		log.Fatalf("%s InitRedis error: %v", logPrefix, err)
	}
	apichat.InitWSService(rdb)
}

func main() {
	config := config.Instance()
	listenAddr, ok := util.GetAvailablePort(config.Service.AddrList)
	if !ok {
		log.Fatalf("%s no port available", logPrefix)
	}

	// 初始化 OpenTelemetry
	p := base.NewOtelProvider(serviceName, config.Otel.CollectorAddr)
	defer func() {
		if err := p.Shutdown(context.Background()); err != nil {
			log.Fatalf("%s Otel provider shutdown error: %v", logPrefix, err)
		}
	}()
	// 初始化 OpenTelemetry Tracing
	tracer, tcfg := tracing.NewServerTracer()

	h := server.New(
		server.WithHostPorts(listenAddr),
		server.WithHandleMethodNotAllowed(true),
		tracer,
	)

	h.Use(cors.New(cors.Config{
		AllowOrigins:     []string{"*"},
		AllowCredentials: true,
		AllowMethods:     []string{"GET", "POST", "PUT", "DELETE", "OPTIONS"},
		AllowHeaders:     []string{"*"},
		ExposeHeaders:    []string{"Content-Length"},
		MaxAge:           12 * time.Hour,
	}))
	h.Use(tracing.ServerMiddleware(tcfg)) // tracing中间件

	// Sentinel
	initSentinel()
	h.Use(hertzSentinel.SentinelServerMiddleware(
		// customize resource extractor if required
		// method_path by default
		hertzSentinel.WithServerResourceExtractor(func(ctx context.Context, c *app.RequestContext) string {
			return "api"
		}),
		// customize block fallback if required
		// abort with status 429 by default
		hertzSentinel.WithServerBlockFallback(func(ctx context.Context, c *app.RequestContext) {
			log.Printf("frequent requests have been rejected by gateway. clientIP: %s", c.ClientIP())
			c.AbortWithStatusJSON(consts.StatusInternalServerError, map[string]interface{}{
				"code": consts.StatusInternalServerError,
				"err":  "服务器当前处于请求高峰。请稍后再试",
			})
		}),
	))

	h.Static("/static", "./uploads")

	router.GeneratedRegister(h)
	h.Spin()
}

func initSentinel() {
	err := sentinel.InitDefault()
	if err != nil {
		log.Fatalf("Unexpected error: %+v", err)
	}
	_, err = flow.LoadRules([]*flow.Rule{
		{
			Resource:               "api",
			Threshold:              0.0,
			TokenCalculateStrategy: flow.Direct,
			ControlBehavior:        flow.Reject,
			StatIntervalInMs:       1000,
		},
	})
	if err != nil {
		log.Fatalf("Unexpected error: %+v", err)
		return
	}
}
