// Code generated by hertz generator.

package api

import (
	"context"

	ai "StreamCore/api/model/ai"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// CreateBot .
// @router /ai/bot [POST]
func CreateBot(ctx context.Context, c *app.RequestContext) {
	var err error
	var req ai.CreateBotReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(ai.CreateBotResp)

	c.JSON(consts.StatusOK, resp)
}

// UpdateBot .
// @router /ai/bot [PUT]
func UpdateBot(ctx context.Context, c *app.RequestContext) {
	var err error
	var req ai.UpdateBotReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(ai.UpdateBotResp)

	c.JSON(consts.StatusOK, resp)
}

// ListBots .
// @router /ai/bots [GET]
func ListBots(ctx context.Context, c *app.RequestContext) {
	var err error
	var req ai.ListBotsReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(ai.ListBotsResp)

	c.JSON(consts.StatusOK, resp)
}

// GetBot .
// @router /ai/bot/:bot_id [GET]
func GetBot(ctx context.Context, c *app.RequestContext) {
	var err error
	var req ai.GetBotReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(ai.GetBotResp)

	c.JSON(consts.StatusOK, resp)
}

// DeleteBot .
// @router /ai/bot/:bot_id [DELETE]
func DeleteBot(ctx context.Context, c *app.RequestContext) {
	var err error
	var req ai.DeleteBotReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(ai.DeleteBotResp)

	c.JSON(consts.StatusOK, resp)
}

// AddBotToGroup .
// @router /ai/bot/group [POST]
func AddBotToGroup(ctx context.Context, c *app.RequestContext) {
	var err error
	var req ai.AddBotToGroupReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(ai.AddBotToGroupResp)

	c.JSON(consts.StatusOK, resp)
}

// RemoveBotFromGroup .
// @router /ai/bot/group [DELETE]
func RemoveBotFromGroup(ctx context.Context, c *app.RequestContext) {
	var err error
	var req ai.RemoveBotFromGroupReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(ai.RemoveBotFromGroupResp)

	c.JSON(consts.StatusOK, resp)
}

// ListGroupBots .
// @router /ai/group/:group_id/bots [GET]
func ListGroupBots(ctx context.Context, c *app.RequestContext) {
	var err error
	var req ai.ListGroupBotsReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(ai.ListGroupBotsResp)

	c.JSON(consts.StatusOK, resp)
}

// RegisterMCPServer .
// @router /ai/mcp/server [POST]
func RegisterMCPServer(ctx context.Context, c *app.RequestContext) {
	var err error
	var req ai.RegisterMCPServerReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(ai.RegisterMCPServerResp)

	c.JSON(consts.StatusOK, resp)
}

// RefreshMCPServer .
// @router /ai/mcp/server/refresh [POST]
func RefreshMCPServer(ctx context.Context, c *app.RequestContext) {
	var err error
	var req ai.RefreshMCPServerReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(ai.RefreshMCPServerResp)

	c.JSON(consts.StatusOK, resp)
}

// ListMCPServers .
// @router /ai/mcp/servers [GET]
func ListMCPServers(ctx context.Context, c *app.RequestContext) {
	var err error
	var req ai.ListMCPServersReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(ai.ListMCPServersResp)

	c.JSON(consts.StatusOK, resp)
}

// DeleteMCPServer .
// @router /ai/mcp/server/:server_id [DELETE]
func DeleteMCPServer(ctx context.Context, c *app.RequestContext) {
	var err error
	var req ai.DeleteMCPServerReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(ai.DeleteMCPServerResp)

	c.JSON(consts.StatusOK, resp)
}

// ListTools .
// @router /ai/tools [GET]
func ListTools(ctx context.Context, c *app.RequestContext) {
	var err error
	var req ai.ListToolsReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(ai.ListToolsResp)

	c.JSON(consts.StatusOK, resp)
}

// SaveCredential .
// @router /ai/credential [POST]
func SaveCredential(ctx context.Context, c *app.RequestContext) {
	var err error
	var req ai.SaveCredentialReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(ai.SaveCredentialResp)

	c.JSON(consts.StatusOK, resp)
}

// DeleteCredential .
// @router /ai/credential/:credential_id [DELETE]
func DeleteCredential(ctx context.Context, c *app.RequestContext) {
	var err error
	var req ai.DeleteCredentialReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(ai.DeleteCredentialResp)

	c.JSON(consts.StatusOK, resp)
}

// ListCredentials .
// @router /ai/credentials [GET]
func ListCredentials(ctx context.Context, c *app.RequestContext) {
	var err error
	var req ai.ListCredentialsReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(ai.ListCredentialsResp)

	c.JSON(consts.StatusOK, resp)
}
