// Code generated by thriftgo (0.4.5). DO NOT EDIT.

package common

import (
	"fmt"
)

type BaseResp struct {
	Code int32  `thrift:"code,1,required" frugal:"1,required,i32" json:"code"`
	Msg  string `thrift:"msg,2,required" frugal:"2,required,string" json:"msg"`
}

func NewBaseResp() *BaseResp {
	return &BaseResp{}
}

func (p *BaseResp) InitDefault() {
}

func (p *BaseResp) GetCode() (v int32) {
	return p.Code
}

func (p *BaseResp) GetMsg() (v string) {
	return p.Msg
}
func (p *BaseResp) SetCode(val int32) {
	p.Code = val
}
func (p *BaseResp) SetMsg(val string) {
	p.Msg = val
}

func (p *BaseResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BaseResp(%+v)", *p)
}

var fieldIDToName_BaseResp = map[int16]string{
	1: "code",
	2: "msg",
}

type UserInfo struct {
	CreatedAt string `thrift:"created_at,1,required" frugal:"1,required,string" json:"created_at"`
	UpdatedAt string `thrift:"updated_at,2,required" frugal:"2,required,string" json:"updated_at"`
	DeletedAt string `thrift:"deleted_at,3,required" frugal:"3,required,string" json:"deleted_at"`
	Id        string `thrift:"id,4,required" frugal:"4,required,string" json:"id"`
	Username  string `thrift:"username,5,required" frugal:"5,required,string" json:"username"`
	AvatarUrl string `thrift:"avatar_url,6,required" frugal:"6,required,string" json:"avatar_url"`
}

func NewUserInfo() *UserInfo {
	return &UserInfo{}
}

func (p *UserInfo) InitDefault() {
}

func (p *UserInfo) GetCreatedAt() (v string) {
	return p.CreatedAt
}

func (p *UserInfo) GetUpdatedAt() (v string) {
	return p.UpdatedAt
}

func (p *UserInfo) GetDeletedAt() (v string) {
	return p.DeletedAt
}

func (p *UserInfo) GetId() (v string) {
	return p.Id
}

func (p *UserInfo) GetUsername() (v string) {
	return p.Username
}

func (p *UserInfo) GetAvatarUrl() (v string) {
	return p.AvatarUrl
}
func (p *UserInfo) SetCreatedAt(val string) {
	p.CreatedAt = val
}
func (p *UserInfo) SetUpdatedAt(val string) {
	p.UpdatedAt = val
}
func (p *UserInfo) SetDeletedAt(val string) {
	p.DeletedAt = val
}
func (p *UserInfo) SetId(val string) {
	p.Id = val
}
func (p *UserInfo) SetUsername(val string) {
	p.Username = val
}
func (p *UserInfo) SetAvatarUrl(val string) {
	p.AvatarUrl = val
}

func (p *UserInfo) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserInfo(%+v)", *p)
}

var fieldIDToName_UserInfo = map[int16]string{
	1: "created_at",
	2: "updated_at",
	3: "deleted_at",
	4: "id",
	5: "username",
	6: "avatar_url",
}

type TokenInfo struct {
	AccessToken  string `thrift:"access_token,1,required" frugal:"1,required,string" json:"access_token"`
	RefreshToken string `thrift:"refresh_token,2,required" frugal:"2,required,string" json:"refresh_token"`
}

func NewTokenInfo() *TokenInfo {
	return &TokenInfo{}
}

func (p *TokenInfo) InitDefault() {
}

func (p *TokenInfo) GetAccessToken() (v string) {
	return p.AccessToken
}

func (p *TokenInfo) GetRefreshToken() (v string) {
	return p.RefreshToken
}
func (p *TokenInfo) SetAccessToken(val string) {
	p.AccessToken = val
}
func (p *TokenInfo) SetRefreshToken(val string) {
	p.RefreshToken = val
}

func (p *TokenInfo) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TokenInfo(%+v)", *p)
}

var fieldIDToName_TokenInfo = map[int16]string{
	1: "access_token",
	2: "refresh_token",
}

type VideoInfo struct {
	CreatedAt    string `thrift:"created_at,1,required" frugal:"1,required,string" json:"created_at"`
	UpdatedAt    string `thrift:"updated_at,2,required" frugal:"2,required,string" json:"updated_at"`
	DeletedAt    string `thrift:"deleted_at,3,required" frugal:"3,required,string" json:"deleted_at"`
	Id           string `thrift:"id,4,required" frugal:"4,required,string" json:"id"`
	UserId       string `thrift:"user_id,5,required" frugal:"5,required,string" json:"user_id"`
	VideoUrl     string `thrift:"video_url,6,required" frugal:"6,required,string" json:"video_url"`
	CoverUrl     string `thrift:"cover_url,7,required" frugal:"7,required,string" json:"cover_url"`
	Title        string `thrift:"title,8,required" frugal:"8,required,string" json:"title"`
	Description  string `thrift:"description,9,required" frugal:"9,required,string" json:"description"`
	VisitCount   int32  `thrift:"visit_count,10,required" frugal:"10,required,i32" json:"visit_count"`
	LikeCount    int32  `thrift:"like_count,11,required" frugal:"11,required,i32" json:"like_count"`
	CommentCount int32  `thrift:"comment_count,12,required" frugal:"12,required,i32" json:"comment_count"`
}

func NewVideoInfo() *VideoInfo {
	return &VideoInfo{}
}

func (p *VideoInfo) InitDefault() {
}

func (p *VideoInfo) GetCreatedAt() (v string) {
	return p.CreatedAt
}

func (p *VideoInfo) GetUpdatedAt() (v string) {
	return p.UpdatedAt
}

func (p *VideoInfo) GetDeletedAt() (v string) {
	return p.DeletedAt
}

func (p *VideoInfo) GetId() (v string) {
	return p.Id
}

func (p *VideoInfo) GetUserId() (v string) {
	return p.UserId
}

func (p *VideoInfo) GetVideoUrl() (v string) {
	return p.VideoUrl
}

func (p *VideoInfo) GetCoverUrl() (v string) {
	return p.CoverUrl
}

func (p *VideoInfo) GetTitle() (v string) {
	return p.Title
}

func (p *VideoInfo) GetDescription() (v string) {
	return p.Description
}

func (p *VideoInfo) GetVisitCount() (v int32) {
	return p.VisitCount
}

func (p *VideoInfo) GetLikeCount() (v int32) {
	return p.LikeCount
}

func (p *VideoInfo) GetCommentCount() (v int32) {
	return p.CommentCount
}
func (p *VideoInfo) SetCreatedAt(val string) {
	p.CreatedAt = val
}
func (p *VideoInfo) SetUpdatedAt(val string) {
	p.UpdatedAt = val
}
func (p *VideoInfo) SetDeletedAt(val string) {
	p.DeletedAt = val
}
func (p *VideoInfo) SetId(val string) {
	p.Id = val
}
func (p *VideoInfo) SetUserId(val string) {
	p.UserId = val
}
func (p *VideoInfo) SetVideoUrl(val string) {
	p.VideoUrl = val
}
func (p *VideoInfo) SetCoverUrl(val string) {
	p.CoverUrl = val
}
func (p *VideoInfo) SetTitle(val string) {
	p.Title = val
}
func (p *VideoInfo) SetDescription(val string) {
	p.Description = val
}
func (p *VideoInfo) SetVisitCount(val int32) {
	p.VisitCount = val
}
func (p *VideoInfo) SetLikeCount(val int32) {
	p.LikeCount = val
}
func (p *VideoInfo) SetCommentCount(val int32) {
	p.CommentCount = val
}

func (p *VideoInfo) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VideoInfo(%+v)", *p)
}

var fieldIDToName_VideoInfo = map[int16]string{
	1:  "created_at",
	2:  "updated_at",
	3:  "deleted_at",
	4:  "id",
	5:  "user_id",
	6:  "video_url",
	7:  "cover_url",
	8:  "title",
	9:  "description",
	10: "visit_count",
	11: "like_count",
	12: "comment_count",
}

type CommentInfo struct {
	CreatedAt  string `thrift:"created_at,1,required" frugal:"1,required,string" json:"created_at"`
	UpdatedAt  string `thrift:"updated_at,2,required" frugal:"2,required,string" json:"updated_at"`
	DeletedAt  string `thrift:"deleted_at,3,required" frugal:"3,required,string" json:"deleted_at"`
	Id         string `thrift:"id,4,required" frugal:"4,required,string" json:"id"`
	UserId     string `thrift:"user_id,5,required" frugal:"5,required,string" json:"user_id"`
	VideoId    string `thrift:"video_id,6,required" frugal:"6,required,string" json:"video_id"`
	ParentId   string `thrift:"parent_id,7,required" frugal:"7,required,string" json:"parent_id"`
	LikeCount  int32  `thrift:"like_count,8,required" frugal:"8,required,i32" json:"like_count"`
	ChildCount int32  `thrift:"child_count,9,required" frugal:"9,required,i32" json:"child_count"`
	Content    string `thrift:"content,10,required" frugal:"10,required,string" json:"content"`
}

func NewCommentInfo() *CommentInfo {
	return &CommentInfo{}
}

func (p *CommentInfo) InitDefault() {
}

func (p *CommentInfo) GetCreatedAt() (v string) {
	return p.CreatedAt
}

func (p *CommentInfo) GetUpdatedAt() (v string) {
	return p.UpdatedAt
}

func (p *CommentInfo) GetDeletedAt() (v string) {
	return p.DeletedAt
}

func (p *CommentInfo) GetId() (v string) {
	return p.Id
}

func (p *CommentInfo) GetUserId() (v string) {
	return p.UserId
}

func (p *CommentInfo) GetVideoId() (v string) {
	return p.VideoId
}

func (p *CommentInfo) GetParentId() (v string) {
	return p.ParentId
}

func (p *CommentInfo) GetLikeCount() (v int32) {
	return p.LikeCount
}

func (p *CommentInfo) GetChildCount() (v int32) {
	return p.ChildCount
}

func (p *CommentInfo) GetContent() (v string) {
	return p.Content
}
func (p *CommentInfo) SetCreatedAt(val string) {
	p.CreatedAt = val
}
func (p *CommentInfo) SetUpdatedAt(val string) {
	p.UpdatedAt = val
}
func (p *CommentInfo) SetDeletedAt(val string) {
	p.DeletedAt = val
}
func (p *CommentInfo) SetId(val string) {
	p.Id = val
}
func (p *CommentInfo) SetUserId(val string) {
	p.UserId = val
}
func (p *CommentInfo) SetVideoId(val string) {
	p.VideoId = val
}
func (p *CommentInfo) SetParentId(val string) {
	p.ParentId = val
}
func (p *CommentInfo) SetLikeCount(val int32) {
	p.LikeCount = val
}
func (p *CommentInfo) SetChildCount(val int32) {
	p.ChildCount = val
}
func (p *CommentInfo) SetContent(val string) {
	p.Content = val
}

func (p *CommentInfo) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CommentInfo(%+v)", *p)
}

var fieldIDToName_CommentInfo = map[int16]string{
	1:  "created_at",
	2:  "updated_at",
	3:  "deleted_at",
	4:  "id",
	5:  "user_id",
	6:  "video_id",
	7:  "parent_id",
	8:  "like_count",
	9:  "child_count",
	10: "content",
}

type SocialUserInfo struct {
	Id        string `thrift:"id,1,required" frugal:"1,required,string" json:"id"`
	Username  string `thrift:"username,2,required" frugal:"2,required,string" json:"username"`
	AvatarUrl string `thrift:"avatar_url,3,required" frugal:"3,required,string" json:"avatar_url"`
}

func NewSocialUserInfo() *SocialUserInfo {
	return &SocialUserInfo{}
}

func (p *SocialUserInfo) InitDefault() {
}

func (p *SocialUserInfo) GetId() (v string) {
	return p.Id
}

func (p *SocialUserInfo) GetUsername() (v string) {
	return p.Username
}

func (p *SocialUserInfo) GetAvatarUrl() (v string) {
	return p.AvatarUrl
}
func (p *SocialUserInfo) SetId(val string) {
	p.Id = val
}
func (p *SocialUserInfo) SetUsername(val string) {
	p.Username = val
}
func (p *SocialUserInfo) SetAvatarUrl(val string) {
	p.AvatarUrl = val
}

func (p *SocialUserInfo) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SocialUserInfo(%+v)", *p)
}

var fieldIDToName_SocialUserInfo = map[int16]string{
	1: "id",
	2: "username",
	3: "avatar_url",
}

type BotInfo struct {
	BotId        string   `thrift:"bot_id,1,required" frugal:"1,required,string" json:"bot_id"`
	BotName      string   `thrift:"bot_name,2,required" frugal:"2,required,string" json:"bot_name"`
	AvatarUrl    string   `thrift:"avatar_url,3,required" frugal:"3,required,string" json:"avatar_url"`
	Description  string   `thrift:"description,4,required" frugal:"4,required,string" json:"description"`
	SystemPrompt string   `thrift:"system_prompt,5,required" frugal:"5,required,string" json:"system_prompt"`
	Provider     string   `thrift:"provider,6,required" frugal:"6,required,string" json:"provider"`
	ModelName    *string  `thrift:"model_name,7,optional" frugal:"7,optional,string" json:"model_name,omitempty"`
	TriggerMode  int32    `thrift:"trigger_mode,8,required" frugal:"8,required,i32" json:"trigger_mode"`
	ToolIds      []string `thrift:"tool_ids,9,required" frugal:"9,required,list<string>" json:"tool_ids"`
	CreatedAt    string   `thrift:"created_at,10,required" frugal:"10,required,string" json:"created_at"`
	UpdatedAt    string   `thrift:"updated_at,11,required" frugal:"11,required,string" json:"updated_at"`
}

func NewBotInfo() *BotInfo {
	return &BotInfo{}
}

func (p *BotInfo) InitDefault() {
}

func (p *BotInfo) GetBotId() (v string) {
	return p.BotId
}

func (p *BotInfo) GetBotName() (v string) {
	return p.BotName
}

func (p *BotInfo) GetAvatarUrl() (v string) {
	return p.AvatarUrl
}

func (p *BotInfo) GetDescription() (v string) {
	return p.Description
}

func (p *BotInfo) GetSystemPrompt() (v string) {
	return p.SystemPrompt
}

func (p *BotInfo) GetProvider() (v string) {
	return p.Provider
}

var BotInfo_ModelName_DEFAULT string

func (p *BotInfo) GetModelName() (v string) {
	if !p.IsSetModelName() {
		return BotInfo_ModelName_DEFAULT
	}
	return *p.ModelName
}

func (p *BotInfo) GetTriggerMode() (v int32) {
	return p.TriggerMode
}

func (p *BotInfo) GetToolIds() (v []string) {
	return p.ToolIds
}

func (p *BotInfo) GetCreatedAt() (v string) {
	return p.CreatedAt
}

func (p *BotInfo) GetUpdatedAt() (v string) {
	return p.UpdatedAt
}
func (p *BotInfo) SetBotId(val string) {
	p.BotId = val
}
func (p *BotInfo) SetBotName(val string) {
	p.BotName = val
}
func (p *BotInfo) SetAvatarUrl(val string) {
	p.AvatarUrl = val
}
func (p *BotInfo) SetDescription(val string) {
	p.Description = val
}
func (p *BotInfo) SetSystemPrompt(val string) {
	p.SystemPrompt = val
}
func (p *BotInfo) SetProvider(val string) {
	p.Provider = val
}
func (p *BotInfo) SetModelName(val *string) {
	p.ModelName = val
}
func (p *BotInfo) SetTriggerMode(val int32) {
	p.TriggerMode = val
}
func (p *BotInfo) SetToolIds(val []string) {
	p.ToolIds = val
}
func (p *BotInfo) SetCreatedAt(val string) {
	p.CreatedAt = val
}
func (p *BotInfo) SetUpdatedAt(val string) {
	p.UpdatedAt = val
}

func (p *BotInfo) IsSetModelName() bool {
	return p.ModelName != nil
}

func (p *BotInfo) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BotInfo(%+v)", *p)
}

var fieldIDToName_BotInfo = map[int16]string{
	1:  "bot_id",
	2:  "bot_name",
	3:  "avatar_url",
	4:  "description",
	5:  "system_prompt",
	6:  "provider",
	7:  "model_name",
	8:  "trigger_mode",
	9:  "tool_ids",
	10: "created_at",
	11: "updated_at",
}

type MCPToolInfo struct {
	ToolId      string `thrift:"tool_id,1,required" frugal:"1,required,string" json:"tool_id"`
	ToolName    string `thrift:"tool_name,2,required" frugal:"2,required,string" json:"tool_name"`
	Description string `thrift:"description,3,required" frugal:"3,required,string" json:"description"`
	InputSchema string `thrift:"input_schema,4,required" frugal:"4,required,string" json:"input_schema"`
	ServerName  string `thrift:"server_name,5,required" frugal:"5,required,string" json:"server_name"`
	ServerId    int64  `thrift:"server_id,6,required" frugal:"6,required,i64" json:"server_id"`
}

func NewMCPToolInfo() *MCPToolInfo {
	return &MCPToolInfo{}
}

func (p *MCPToolInfo) InitDefault() {
}

func (p *MCPToolInfo) GetToolId() (v string) {
	return p.ToolId
}

func (p *MCPToolInfo) GetToolName() (v string) {
	return p.ToolName
}

func (p *MCPToolInfo) GetDescription() (v string) {
	return p.Description
}

func (p *MCPToolInfo) GetInputSchema() (v string) {
	return p.InputSchema
}

func (p *MCPToolInfo) GetServerName() (v string) {
	return p.ServerName
}

func (p *MCPToolInfo) GetServerId() (v int64) {
	return p.ServerId
}
func (p *MCPToolInfo) SetToolId(val string) {
	p.ToolId = val
}
func (p *MCPToolInfo) SetToolName(val string) {
	p.ToolName = val
}
func (p *MCPToolInfo) SetDescription(val string) {
	p.Description = val
}
func (p *MCPToolInfo) SetInputSchema(val string) {
	p.InputSchema = val
}
func (p *MCPToolInfo) SetServerName(val string) {
	p.ServerName = val
}
func (p *MCPToolInfo) SetServerId(val int64) {
	p.ServerId = val
}

func (p *MCPToolInfo) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MCPToolInfo(%+v)", *p)
}

var fieldIDToName_MCPToolInfo = map[int16]string{
	1: "tool_id",
	2: "tool_name",
	3: "description",
	4: "input_schema",
	5: "server_name",
	6: "server_id",
}

type MCPServerInfo struct {
	ServerId        int64  `thrift:"server_id,1,required" frugal:"1,required,i64" json:"server_id"`
	ServerName      string `thrift:"server_name,2,required" frugal:"2,required,string" json:"server_name"`
	ServerUrl       string `thrift:"server_url,3,required" frugal:"3,required,string" json:"server_url"`
	SyncIntervalSec int32  `thrift:"sync_interval_sec,4,required" frugal:"4,required,i32" json:"sync_interval_sec"`
	LastSyncedAt    string `thrift:"last_synced_at,5,required" frugal:"5,required,string" json:"last_synced_at"`
	Status          int32  `thrift:"status,6,required" frugal:"6,required,i32" json:"status"`
	CreatedAt       string `thrift:"created_at,7,required" frugal:"7,required,string" json:"created_at"`
	UpdatedAt       string `thrift:"updated_at,8,required" frugal:"8,required,string" json:"updated_at"`
}

func NewMCPServerInfo() *MCPServerInfo {
	return &MCPServerInfo{}
}

func (p *MCPServerInfo) InitDefault() {
}

func (p *MCPServerInfo) GetServerId() (v int64) {
	return p.ServerId
}

func (p *MCPServerInfo) GetServerName() (v string) {
	return p.ServerName
}

func (p *MCPServerInfo) GetServerUrl() (v string) {
	return p.ServerUrl
}

func (p *MCPServerInfo) GetSyncIntervalSec() (v int32) {
	return p.SyncIntervalSec
}

func (p *MCPServerInfo) GetLastSyncedAt() (v string) {
	return p.LastSyncedAt
}

func (p *MCPServerInfo) GetStatus() (v int32) {
	return p.Status
}

func (p *MCPServerInfo) GetCreatedAt() (v string) {
	return p.CreatedAt
}

func (p *MCPServerInfo) GetUpdatedAt() (v string) {
	return p.UpdatedAt
}
func (p *MCPServerInfo) SetServerId(val int64) {
	p.ServerId = val
}
func (p *MCPServerInfo) SetServerName(val string) {
	p.ServerName = val
}
func (p *MCPServerInfo) SetServerUrl(val string) {
	p.ServerUrl = val
}
func (p *MCPServerInfo) SetSyncIntervalSec(val int32) {
	p.SyncIntervalSec = val
}
func (p *MCPServerInfo) SetLastSyncedAt(val string) {
	p.LastSyncedAt = val
}
func (p *MCPServerInfo) SetStatus(val int32) {
	p.Status = val
}
func (p *MCPServerInfo) SetCreatedAt(val string) {
	p.CreatedAt = val
}
func (p *MCPServerInfo) SetUpdatedAt(val string) {
	p.UpdatedAt = val
}

func (p *MCPServerInfo) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MCPServerInfo(%+v)", *p)
}

var fieldIDToName_MCPServerInfo = map[int16]string{
	1: "server_id",
	2: "server_name",
	3: "server_url",
	4: "sync_interval_sec",
	5: "last_synced_at",
	6: "status",
	7: "created_at",
	8: "updated_at",
}
