// Code generated by thriftgo (0.4.5). DO NOT EDIT.

package ai

import (
	"StreamCore/kitex_gen/common"
	"context"
	"fmt"
)

type ProcessMessageReq struct {
	RoomId         string `thrift:"room_id,1,required" frugal:"1,required,string" json:"room_id"`
	MsgId          int64  `thrift:"msg_id,2,required" frugal:"2,required,i64" json:"msg_id"`
	FromUid        string `thrift:"from_uid,3,required" frugal:"3,required,string" json:"from_uid"`
	Content        string `thrift:"content,4,required" frugal:"4,required,string" json:"content"`
	Timestamp      int64  `thrift:"timestamp,5,required" frugal:"5,required,i64" json:"timestamp"`
	MentionedBotId string `thrift:"mentioned_bot_id,6,required" frugal:"6,required,string" json:"mentioned_bot_id"`
}

func NewProcessMessageReq() *ProcessMessageReq {
	return &ProcessMessageReq{}
}

func (p *ProcessMessageReq) InitDefault() {
}

func (p *ProcessMessageReq) GetRoomId() (v string) {
	return p.RoomId
}

func (p *ProcessMessageReq) GetMsgId() (v int64) {
	return p.MsgId
}

func (p *ProcessMessageReq) GetFromUid() (v string) {
	return p.FromUid
}

func (p *ProcessMessageReq) GetContent() (v string) {
	return p.Content
}

func (p *ProcessMessageReq) GetTimestamp() (v int64) {
	return p.Timestamp
}

func (p *ProcessMessageReq) GetMentionedBotId() (v string) {
	return p.MentionedBotId
}
func (p *ProcessMessageReq) SetRoomId(val string) {
	p.RoomId = val
}
func (p *ProcessMessageReq) SetMsgId(val int64) {
	p.MsgId = val
}
func (p *ProcessMessageReq) SetFromUid(val string) {
	p.FromUid = val
}
func (p *ProcessMessageReq) SetContent(val string) {
	p.Content = val
}
func (p *ProcessMessageReq) SetTimestamp(val int64) {
	p.Timestamp = val
}
func (p *ProcessMessageReq) SetMentionedBotId(val string) {
	p.MentionedBotId = val
}

func (p *ProcessMessageReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ProcessMessageReq(%+v)", *p)
}

var fieldIDToName_ProcessMessageReq = map[int16]string{
	1: "room_id",
	2: "msg_id",
	3: "from_uid",
	4: "content",
	5: "timestamp",
	6: "mentioned_bot_id",
}

type ProcessMessageResp struct {
	Base         *common.BaseResp `thrift:"base,1,required" frugal:"1,required,common.BaseResp" json:"base"`
	WillRespond  *bool            `thrift:"will_respond,2,optional" frugal:"2,optional,bool" json:"will_respond,omitempty"`
	EstimatedSec *string          `thrift:"estimated_sec,3,optional" frugal:"3,optional,string" json:"estimated_sec,omitempty"`
}

func NewProcessMessageResp() *ProcessMessageResp {
	return &ProcessMessageResp{}
}

func (p *ProcessMessageResp) InitDefault() {
}

var ProcessMessageResp_Base_DEFAULT *common.BaseResp

func (p *ProcessMessageResp) GetBase() (v *common.BaseResp) {
	if !p.IsSetBase() {
		return ProcessMessageResp_Base_DEFAULT
	}
	return p.Base
}

var ProcessMessageResp_WillRespond_DEFAULT bool

func (p *ProcessMessageResp) GetWillRespond() (v bool) {
	if !p.IsSetWillRespond() {
		return ProcessMessageResp_WillRespond_DEFAULT
	}
	return *p.WillRespond
}

var ProcessMessageResp_EstimatedSec_DEFAULT string

func (p *ProcessMessageResp) GetEstimatedSec() (v string) {
	if !p.IsSetEstimatedSec() {
		return ProcessMessageResp_EstimatedSec_DEFAULT
	}
	return *p.EstimatedSec
}
func (p *ProcessMessageResp) SetBase(val *common.BaseResp) {
	p.Base = val
}
func (p *ProcessMessageResp) SetWillRespond(val *bool) {
	p.WillRespond = val
}
func (p *ProcessMessageResp) SetEstimatedSec(val *string) {
	p.EstimatedSec = val
}

func (p *ProcessMessageResp) IsSetBase() bool {
	return p.Base != nil
}

func (p *ProcessMessageResp) IsSetWillRespond() bool {
	return p.WillRespond != nil
}

func (p *ProcessMessageResp) IsSetEstimatedSec() bool {
	return p.EstimatedSec != nil
}

func (p *ProcessMessageResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ProcessMessageResp(%+v)", *p)
}

var fieldIDToName_ProcessMessageResp = map[int16]string{
	1: "base",
	2: "will_respond",
	3: "estimated_sec",
}

type CreateBotReq struct {
	BotName      string   `thrift:"bot_name,1,required" frugal:"1,required,string" json:"bot_name"`
	SystemPrompt string   `thrift:"system_prompt,2,required" frugal:"2,required,string" json:"system_prompt"`
	Provider     string   `thrift:"provider,3,required" frugal:"3,required,string" json:"provider"`
	ModelName    *string  `thrift:"model_name,4,optional" frugal:"4,optional,string" json:"model_name,omitempty"`
	TriggerMode  int32    `thrift:"trigger_mode,5,required" frugal:"5,required,i32" json:"trigger_mode"`
	Description  *string  `thrift:"description,6,optional" frugal:"6,optional,string" json:"description,omitempty"`
	AvatarUrl    *string  `thrift:"avatar_url,7,optional" frugal:"7,optional,string" json:"avatar_url,omitempty"`
	ToolIds      []string `thrift:"tool_ids,8,optional" frugal:"8,optional,list<string>" json:"tool_ids,omitempty"`
}

func NewCreateBotReq() *CreateBotReq {
	return &CreateBotReq{}
}

func (p *CreateBotReq) InitDefault() {
}

func (p *CreateBotReq) GetBotName() (v string) {
	return p.BotName
}

func (p *CreateBotReq) GetSystemPrompt() (v string) {
	return p.SystemPrompt
}

func (p *CreateBotReq) GetProvider() (v string) {
	return p.Provider
}

var CreateBotReq_ModelName_DEFAULT string

func (p *CreateBotReq) GetModelName() (v string) {
	if !p.IsSetModelName() {
		return CreateBotReq_ModelName_DEFAULT
	}
	return *p.ModelName
}

func (p *CreateBotReq) GetTriggerMode() (v int32) {
	return p.TriggerMode
}

var CreateBotReq_Description_DEFAULT string

func (p *CreateBotReq) GetDescription() (v string) {
	if !p.IsSetDescription() {
		return CreateBotReq_Description_DEFAULT
	}
	return *p.Description
}

var CreateBotReq_AvatarUrl_DEFAULT string

func (p *CreateBotReq) GetAvatarUrl() (v string) {
	if !p.IsSetAvatarUrl() {
		return CreateBotReq_AvatarUrl_DEFAULT
	}
	return *p.AvatarUrl
}

var CreateBotReq_ToolIds_DEFAULT []string

func (p *CreateBotReq) GetToolIds() (v []string) {
	if !p.IsSetToolIds() {
		return CreateBotReq_ToolIds_DEFAULT
	}
	return p.ToolIds
}
func (p *CreateBotReq) SetBotName(val string) {
	p.BotName = val
}
func (p *CreateBotReq) SetSystemPrompt(val string) {
	p.SystemPrompt = val
}
func (p *CreateBotReq) SetProvider(val string) {
	p.Provider = val
}
func (p *CreateBotReq) SetModelName(val *string) {
	p.ModelName = val
}
func (p *CreateBotReq) SetTriggerMode(val int32) {
	p.TriggerMode = val
}
func (p *CreateBotReq) SetDescription(val *string) {
	p.Description = val
}
func (p *CreateBotReq) SetAvatarUrl(val *string) {
	p.AvatarUrl = val
}
func (p *CreateBotReq) SetToolIds(val []string) {
	p.ToolIds = val
}

func (p *CreateBotReq) IsSetModelName() bool {
	return p.ModelName != nil
}

func (p *CreateBotReq) IsSetDescription() bool {
	return p.Description != nil
}

func (p *CreateBotReq) IsSetAvatarUrl() bool {
	return p.AvatarUrl != nil
}

func (p *CreateBotReq) IsSetToolIds() bool {
	return p.ToolIds != nil
}

func (p *CreateBotReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CreateBotReq(%+v)", *p)
}

var fieldIDToName_CreateBotReq = map[int16]string{
	1: "bot_name",
	2: "system_prompt",
	3: "provider",
	4: "model_name",
	5: "trigger_mode",
	6: "description",
	7: "avatar_url",
	8: "tool_ids",
}

type CreateBotResp struct {
	Base *common.BaseResp `thrift:"base,1,required" frugal:"1,required,common.BaseResp" json:"base"`
	Bot  *common.BotInfo  `thrift:"bot,2,optional" frugal:"2,optional,common.BotInfo" json:"bot,omitempty"`
}

func NewCreateBotResp() *CreateBotResp {
	return &CreateBotResp{}
}

func (p *CreateBotResp) InitDefault() {
}

var CreateBotResp_Base_DEFAULT *common.BaseResp

func (p *CreateBotResp) GetBase() (v *common.BaseResp) {
	if !p.IsSetBase() {
		return CreateBotResp_Base_DEFAULT
	}
	return p.Base
}

var CreateBotResp_Bot_DEFAULT *common.BotInfo

func (p *CreateBotResp) GetBot() (v *common.BotInfo) {
	if !p.IsSetBot() {
		return CreateBotResp_Bot_DEFAULT
	}
	return p.Bot
}
func (p *CreateBotResp) SetBase(val *common.BaseResp) {
	p.Base = val
}
func (p *CreateBotResp) SetBot(val *common.BotInfo) {
	p.Bot = val
}

func (p *CreateBotResp) IsSetBase() bool {
	return p.Base != nil
}

func (p *CreateBotResp) IsSetBot() bool {
	return p.Bot != nil
}

func (p *CreateBotResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CreateBotResp(%+v)", *p)
}

var fieldIDToName_CreateBotResp = map[int16]string{
	1: "base",
	2: "bot",
}

type UpdateBotReq struct {
	BotId        string   `thrift:"bot_id,1,required" frugal:"1,required,string" json:"bot_id"`
	BotName      *string  `thrift:"bot_name,2,optional" frugal:"2,optional,string" json:"bot_name,omitempty"`
	SystemPrompt *string  `thrift:"system_prompt,3,optional" frugal:"3,optional,string" json:"system_prompt,omitempty"`
	Provider     *string  `thrift:"provider,4,optional" frugal:"4,optional,string" json:"provider,omitempty"`
	ModelName    *string  `thrift:"model_name,5,optional" frugal:"5,optional,string" json:"model_name,omitempty"`
	TriggerMode  *int32   `thrift:"trigger_mode,6,optional" frugal:"6,optional,i32" json:"trigger_mode,omitempty"`
	Description  *string  `thrift:"description,7,optional" frugal:"7,optional,string" json:"description,omitempty"`
	AvatarUrl    *string  `thrift:"avatar_url,8,optional" frugal:"8,optional,string" json:"avatar_url,omitempty"`
	ToolIds      []string `thrift:"tool_ids,9,optional" frugal:"9,optional,list<string>" json:"tool_ids,omitempty"`
}

func NewUpdateBotReq() *UpdateBotReq {
	return &UpdateBotReq{}
}

func (p *UpdateBotReq) InitDefault() {
}

func (p *UpdateBotReq) GetBotId() (v string) {
	return p.BotId
}

var UpdateBotReq_BotName_DEFAULT string

func (p *UpdateBotReq) GetBotName() (v string) {
	if !p.IsSetBotName() {
		return UpdateBotReq_BotName_DEFAULT
	}
	return *p.BotName
}

var UpdateBotReq_SystemPrompt_DEFAULT string

func (p *UpdateBotReq) GetSystemPrompt() (v string) {
	if !p.IsSetSystemPrompt() {
		return UpdateBotReq_SystemPrompt_DEFAULT
	}
	return *p.SystemPrompt
}

var UpdateBotReq_Provider_DEFAULT string

func (p *UpdateBotReq) GetProvider() (v string) {
	if !p.IsSetProvider() {
		return UpdateBotReq_Provider_DEFAULT
	}
	return *p.Provider
}

var UpdateBotReq_ModelName_DEFAULT string

func (p *UpdateBotReq) GetModelName() (v string) {
	if !p.IsSetModelName() {
		return UpdateBotReq_ModelName_DEFAULT
	}
	return *p.ModelName
}

var UpdateBotReq_TriggerMode_DEFAULT int32

func (p *UpdateBotReq) GetTriggerMode() (v int32) {
	if !p.IsSetTriggerMode() {
		return UpdateBotReq_TriggerMode_DEFAULT
	}
	return *p.TriggerMode
}

var UpdateBotReq_Description_DEFAULT string

func (p *UpdateBotReq) GetDescription() (v string) {
	if !p.IsSetDescription() {
		return UpdateBotReq_Description_DEFAULT
	}
	return *p.Description
}

var UpdateBotReq_AvatarUrl_DEFAULT string

func (p *UpdateBotReq) GetAvatarUrl() (v string) {
	if !p.IsSetAvatarUrl() {
		return UpdateBotReq_AvatarUrl_DEFAULT
	}
	return *p.AvatarUrl
}

var UpdateBotReq_ToolIds_DEFAULT []string

func (p *UpdateBotReq) GetToolIds() (v []string) {
	if !p.IsSetToolIds() {
		return UpdateBotReq_ToolIds_DEFAULT
	}
	return p.ToolIds
}
func (p *UpdateBotReq) SetBotId(val string) {
	p.BotId = val
}
func (p *UpdateBotReq) SetBotName(val *string) {
	p.BotName = val
}
func (p *UpdateBotReq) SetSystemPrompt(val *string) {
	p.SystemPrompt = val
}
func (p *UpdateBotReq) SetProvider(val *string) {
	p.Provider = val
}
func (p *UpdateBotReq) SetModelName(val *string) {
	p.ModelName = val
}
func (p *UpdateBotReq) SetTriggerMode(val *int32) {
	p.TriggerMode = val
}
func (p *UpdateBotReq) SetDescription(val *string) {
	p.Description = val
}
func (p *UpdateBotReq) SetAvatarUrl(val *string) {
	p.AvatarUrl = val
}
func (p *UpdateBotReq) SetToolIds(val []string) {
	p.ToolIds = val
}

func (p *UpdateBotReq) IsSetBotName() bool {
	return p.BotName != nil
}

func (p *UpdateBotReq) IsSetSystemPrompt() bool {
	return p.SystemPrompt != nil
}

func (p *UpdateBotReq) IsSetProvider() bool {
	return p.Provider != nil
}

func (p *UpdateBotReq) IsSetModelName() bool {
	return p.ModelName != nil
}

func (p *UpdateBotReq) IsSetTriggerMode() bool {
	return p.TriggerMode != nil
}

func (p *UpdateBotReq) IsSetDescription() bool {
	return p.Description != nil
}

func (p *UpdateBotReq) IsSetAvatarUrl() bool {
	return p.AvatarUrl != nil
}

func (p *UpdateBotReq) IsSetToolIds() bool {
	return p.ToolIds != nil
}

func (p *UpdateBotReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpdateBotReq(%+v)", *p)
}

var fieldIDToName_UpdateBotReq = map[int16]string{
	1: "bot_id",
	2: "bot_name",
	3: "system_prompt",
	4: "provider",
	5: "model_name",
	6: "trigger_mode",
	7: "description",
	8: "avatar_url",
	9: "tool_ids",
}

type UpdateBotResp struct {
	Base *common.BaseResp `thrift:"base,1,required" frugal:"1,required,common.BaseResp" json:"base"`
	Bot  *common.BotInfo  `thrift:"bot,2,optional" frugal:"2,optional,common.BotInfo" json:"bot,omitempty"`
}

func NewUpdateBotResp() *UpdateBotResp {
	return &UpdateBotResp{}
}

func (p *UpdateBotResp) InitDefault() {
}

var UpdateBotResp_Base_DEFAULT *common.BaseResp

func (p *UpdateBotResp) GetBase() (v *common.BaseResp) {
	if !p.IsSetBase() {
		return UpdateBotResp_Base_DEFAULT
	}
	return p.Base
}

var UpdateBotResp_Bot_DEFAULT *common.BotInfo

func (p *UpdateBotResp) GetBot() (v *common.BotInfo) {
	if !p.IsSetBot() {
		return UpdateBotResp_Bot_DEFAULT
	}
	return p.Bot
}
func (p *UpdateBotResp) SetBase(val *common.BaseResp) {
	p.Base = val
}
func (p *UpdateBotResp) SetBot(val *common.BotInfo) {
	p.Bot = val
}

func (p *UpdateBotResp) IsSetBase() bool {
	return p.Base != nil
}

func (p *UpdateBotResp) IsSetBot() bool {
	return p.Bot != nil
}

func (p *UpdateBotResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpdateBotResp(%+v)", *p)
}

var fieldIDToName_UpdateBotResp = map[int16]string{
	1: "base",
	2: "bot",
}

type ListBotsReq struct {
	PageSize *int32 `thrift:"page_size,1,optional" frugal:"1,optional,i32" json:"page_size,omitempty"`
	Page     *int32 `thrift:"page,2,optional" frugal:"2,optional,i32" json:"page,omitempty"`
}

func NewListBotsReq() *ListBotsReq {
	return &ListBotsReq{}
}

func (p *ListBotsReq) InitDefault() {
}

var ListBotsReq_PageSize_DEFAULT int32

func (p *ListBotsReq) GetPageSize() (v int32) {
	if !p.IsSetPageSize() {
		return ListBotsReq_PageSize_DEFAULT
	}
	return *p.PageSize
}

var ListBotsReq_Page_DEFAULT int32

func (p *ListBotsReq) GetPage() (v int32) {
	if !p.IsSetPage() {
		return ListBotsReq_Page_DEFAULT
	}
	return *p.Page
}
func (p *ListBotsReq) SetPageSize(val *int32) {
	p.PageSize = val
}
func (p *ListBotsReq) SetPage(val *int32) {
	p.Page = val
}

func (p *ListBotsReq) IsSetPageSize() bool {
	return p.PageSize != nil
}

func (p *ListBotsReq) IsSetPage() bool {
	return p.Page != nil
}

func (p *ListBotsReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ListBotsReq(%+v)", *p)
}

var fieldIDToName_ListBotsReq = map[int16]string{
	1: "page_size",
	2: "page",
}

type ListBotsResp struct {
	Base  *common.BaseResp  `thrift:"base,1,required" frugal:"1,required,common.BaseResp" json:"base"`
	Bots  []*common.BotInfo `thrift:"bots,2,optional" frugal:"2,optional,list<common.BotInfo>" json:"bots,omitempty"`
	Total *int32            `thrift:"total,3,optional" frugal:"3,optional,i32" json:"total,omitempty"`
}

func NewListBotsResp() *ListBotsResp {
	return &ListBotsResp{}
}

func (p *ListBotsResp) InitDefault() {
}

var ListBotsResp_Base_DEFAULT *common.BaseResp

func (p *ListBotsResp) GetBase() (v *common.BaseResp) {
	if !p.IsSetBase() {
		return ListBotsResp_Base_DEFAULT
	}
	return p.Base
}

var ListBotsResp_Bots_DEFAULT []*common.BotInfo

func (p *ListBotsResp) GetBots() (v []*common.BotInfo) {
	if !p.IsSetBots() {
		return ListBotsResp_Bots_DEFAULT
	}
	return p.Bots
}

var ListBotsResp_Total_DEFAULT int32

func (p *ListBotsResp) GetTotal() (v int32) {
	if !p.IsSetTotal() {
		return ListBotsResp_Total_DEFAULT
	}
	return *p.Total
}
func (p *ListBotsResp) SetBase(val *common.BaseResp) {
	p.Base = val
}
func (p *ListBotsResp) SetBots(val []*common.BotInfo) {
	p.Bots = val
}
func (p *ListBotsResp) SetTotal(val *int32) {
	p.Total = val
}

func (p *ListBotsResp) IsSetBase() bool {
	return p.Base != nil
}

func (p *ListBotsResp) IsSetBots() bool {
	return p.Bots != nil
}

func (p *ListBotsResp) IsSetTotal() bool {
	return p.Total != nil
}

func (p *ListBotsResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ListBotsResp(%+v)", *p)
}

var fieldIDToName_ListBotsResp = map[int16]string{
	1: "base",
	2: "bots",
	3: "total",
}

type GetBotReq struct {
	BotId string `thrift:"bot_id,1,required" frugal:"1,required,string" json:"bot_id"`
}

func NewGetBotReq() *GetBotReq {
	return &GetBotReq{}
}

func (p *GetBotReq) InitDefault() {
}

func (p *GetBotReq) GetBotId() (v string) {
	return p.BotId
}
func (p *GetBotReq) SetBotId(val string) {
	p.BotId = val
}

func (p *GetBotReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetBotReq(%+v)", *p)
}

var fieldIDToName_GetBotReq = map[int16]string{
	1: "bot_id",
}

type GetBotResp struct {
	Base *common.BaseResp `thrift:"base,1,required" frugal:"1,required,common.BaseResp" json:"base"`
	Bot  *common.BotInfo  `thrift:"bot,2,optional" frugal:"2,optional,common.BotInfo" json:"bot,omitempty"`
}

func NewGetBotResp() *GetBotResp {
	return &GetBotResp{}
}

func (p *GetBotResp) InitDefault() {
}

var GetBotResp_Base_DEFAULT *common.BaseResp

func (p *GetBotResp) GetBase() (v *common.BaseResp) {
	if !p.IsSetBase() {
		return GetBotResp_Base_DEFAULT
	}
	return p.Base
}

var GetBotResp_Bot_DEFAULT *common.BotInfo

func (p *GetBotResp) GetBot() (v *common.BotInfo) {
	if !p.IsSetBot() {
		return GetBotResp_Bot_DEFAULT
	}
	return p.Bot
}
func (p *GetBotResp) SetBase(val *common.BaseResp) {
	p.Base = val
}
func (p *GetBotResp) SetBot(val *common.BotInfo) {
	p.Bot = val
}

func (p *GetBotResp) IsSetBase() bool {
	return p.Base != nil
}

func (p *GetBotResp) IsSetBot() bool {
	return p.Bot != nil
}

func (p *GetBotResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetBotResp(%+v)", *p)
}

var fieldIDToName_GetBotResp = map[int16]string{
	1: "base",
	2: "bot",
}

type DeleteBotReq struct {
	BotId string `thrift:"bot_id,1,required" frugal:"1,required,string" json:"bot_id"`
}

func NewDeleteBotReq() *DeleteBotReq {
	return &DeleteBotReq{}
}

func (p *DeleteBotReq) InitDefault() {
}

func (p *DeleteBotReq) GetBotId() (v string) {
	return p.BotId
}
func (p *DeleteBotReq) SetBotId(val string) {
	p.BotId = val
}

func (p *DeleteBotReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DeleteBotReq(%+v)", *p)
}

var fieldIDToName_DeleteBotReq = map[int16]string{
	1: "bot_id",
}

type DeleteBotResp struct {
	Base *common.BaseResp `thrift:"base,1,required" frugal:"1,required,common.BaseResp" json:"base"`
}

func NewDeleteBotResp() *DeleteBotResp {
	return &DeleteBotResp{}
}

func (p *DeleteBotResp) InitDefault() {
}

var DeleteBotResp_Base_DEFAULT *common.BaseResp

func (p *DeleteBotResp) GetBase() (v *common.BaseResp) {
	if !p.IsSetBase() {
		return DeleteBotResp_Base_DEFAULT
	}
	return p.Base
}
func (p *DeleteBotResp) SetBase(val *common.BaseResp) {
	p.Base = val
}

func (p *DeleteBotResp) IsSetBase() bool {
	return p.Base != nil
}

func (p *DeleteBotResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DeleteBotResp(%+v)", *p)
}

var fieldIDToName_DeleteBotResp = map[int16]string{
	1: "base",
}

type AddBotToGroupReq struct {
	BotId   string `thrift:"bot_id,1,required" frugal:"1,required,string" json:"bot_id"`
	GroupId string `thrift:"group_id,2,required" frugal:"2,required,string" json:"group_id"`
}

func NewAddBotToGroupReq() *AddBotToGroupReq {
	return &AddBotToGroupReq{}
}

func (p *AddBotToGroupReq) InitDefault() {
}

func (p *AddBotToGroupReq) GetBotId() (v string) {
	return p.BotId
}

func (p *AddBotToGroupReq) GetGroupId() (v string) {
	return p.GroupId
}
func (p *AddBotToGroupReq) SetBotId(val string) {
	p.BotId = val
}
func (p *AddBotToGroupReq) SetGroupId(val string) {
	p.GroupId = val
}

func (p *AddBotToGroupReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AddBotToGroupReq(%+v)", *p)
}

var fieldIDToName_AddBotToGroupReq = map[int16]string{
	1: "bot_id",
	2: "group_id",
}

type AddBotToGroupResp struct {
	Base *common.BaseResp `thrift:"base,1,required" frugal:"1,required,common.BaseResp" json:"base"`
}

func NewAddBotToGroupResp() *AddBotToGroupResp {
	return &AddBotToGroupResp{}
}

func (p *AddBotToGroupResp) InitDefault() {
}

var AddBotToGroupResp_Base_DEFAULT *common.BaseResp

func (p *AddBotToGroupResp) GetBase() (v *common.BaseResp) {
	if !p.IsSetBase() {
		return AddBotToGroupResp_Base_DEFAULT
	}
	return p.Base
}
func (p *AddBotToGroupResp) SetBase(val *common.BaseResp) {
	p.Base = val
}

func (p *AddBotToGroupResp) IsSetBase() bool {
	return p.Base != nil
}

func (p *AddBotToGroupResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AddBotToGroupResp(%+v)", *p)
}

var fieldIDToName_AddBotToGroupResp = map[int16]string{
	1: "base",
}

type RemoveBotFromGroupReq struct {
	BotId   string `thrift:"bot_id,1,required" frugal:"1,required,string" json:"bot_id"`
	GroupId string `thrift:"group_id,2,required" frugal:"2,required,string" json:"group_id"`
}

func NewRemoveBotFromGroupReq() *RemoveBotFromGroupReq {
	return &RemoveBotFromGroupReq{}
}

func (p *RemoveBotFromGroupReq) InitDefault() {
}

func (p *RemoveBotFromGroupReq) GetBotId() (v string) {
	return p.BotId
}

func (p *RemoveBotFromGroupReq) GetGroupId() (v string) {
	return p.GroupId
}
func (p *RemoveBotFromGroupReq) SetBotId(val string) {
	p.BotId = val
}
func (p *RemoveBotFromGroupReq) SetGroupId(val string) {
	p.GroupId = val
}

func (p *RemoveBotFromGroupReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RemoveBotFromGroupReq(%+v)", *p)
}

var fieldIDToName_RemoveBotFromGroupReq = map[int16]string{
	1: "bot_id",
	2: "group_id",
}

type RemoveBotFromGroupResp struct {
	Base *common.BaseResp `thrift:"base,1,required" frugal:"1,required,common.BaseResp" json:"base"`
}

func NewRemoveBotFromGroupResp() *RemoveBotFromGroupResp {
	return &RemoveBotFromGroupResp{}
}

func (p *RemoveBotFromGroupResp) InitDefault() {
}

var RemoveBotFromGroupResp_Base_DEFAULT *common.BaseResp

func (p *RemoveBotFromGroupResp) GetBase() (v *common.BaseResp) {
	if !p.IsSetBase() {
		return RemoveBotFromGroupResp_Base_DEFAULT
	}
	return p.Base
}
func (p *RemoveBotFromGroupResp) SetBase(val *common.BaseResp) {
	p.Base = val
}

func (p *RemoveBotFromGroupResp) IsSetBase() bool {
	return p.Base != nil
}

func (p *RemoveBotFromGroupResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RemoveBotFromGroupResp(%+v)", *p)
}

var fieldIDToName_RemoveBotFromGroupResp = map[int16]string{
	1: "base",
}

type ListGroupBotsReq struct {
	GroupId string `thrift:"group_id,1,required" frugal:"1,required,string" json:"group_id"`
}

func NewListGroupBotsReq() *ListGroupBotsReq {
	return &ListGroupBotsReq{}
}

func (p *ListGroupBotsReq) InitDefault() {
}

func (p *ListGroupBotsReq) GetGroupId() (v string) {
	return p.GroupId
}
func (p *ListGroupBotsReq) SetGroupId(val string) {
	p.GroupId = val
}

func (p *ListGroupBotsReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ListGroupBotsReq(%+v)", *p)
}

var fieldIDToName_ListGroupBotsReq = map[int16]string{
	1: "group_id",
}

type ListGroupBotsResp struct {
	Base *common.BaseResp  `thrift:"base,1,required" frugal:"1,required,common.BaseResp" json:"base"`
	Bots []*common.BotInfo `thrift:"bots,2,optional" frugal:"2,optional,list<common.BotInfo>" json:"bots,omitempty"`
}

func NewListGroupBotsResp() *ListGroupBotsResp {
	return &ListGroupBotsResp{}
}

func (p *ListGroupBotsResp) InitDefault() {
}

var ListGroupBotsResp_Base_DEFAULT *common.BaseResp

func (p *ListGroupBotsResp) GetBase() (v *common.BaseResp) {
	if !p.IsSetBase() {
		return ListGroupBotsResp_Base_DEFAULT
	}
	return p.Base
}

var ListGroupBotsResp_Bots_DEFAULT []*common.BotInfo

func (p *ListGroupBotsResp) GetBots() (v []*common.BotInfo) {
	if !p.IsSetBots() {
		return ListGroupBotsResp_Bots_DEFAULT
	}
	return p.Bots
}
func (p *ListGroupBotsResp) SetBase(val *common.BaseResp) {
	p.Base = val
}
func (p *ListGroupBotsResp) SetBots(val []*common.BotInfo) {
	p.Bots = val
}

func (p *ListGroupBotsResp) IsSetBase() bool {
	return p.Base != nil
}

func (p *ListGroupBotsResp) IsSetBots() bool {
	return p.Bots != nil
}

func (p *ListGroupBotsResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ListGroupBotsResp(%+v)", *p)
}

var fieldIDToName_ListGroupBotsResp = map[int16]string{
	1: "base",
	2: "bots",
}

type ListBotGroupsReq struct {
	BotId string `thrift:"bot_id,1,required" frugal:"1,required,string" json:"bot_id"`
}

func NewListBotGroupsReq() *ListBotGroupsReq {
	return &ListBotGroupsReq{}
}

func (p *ListBotGroupsReq) InitDefault() {
}

func (p *ListBotGroupsReq) GetBotId() (v string) {
	return p.BotId
}
func (p *ListBotGroupsReq) SetBotId(val string) {
	p.BotId = val
}

func (p *ListBotGroupsReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ListBotGroupsReq(%+v)", *p)
}

var fieldIDToName_ListBotGroupsReq = map[int16]string{
	1: "bot_id",
}

type ListBotGroupsResp struct {
	Base     *common.BaseResp `thrift:"base,1,required" frugal:"1,required,common.BaseResp" json:"base"`
	GroupIds []string         `thrift:"group_ids,2,optional" frugal:"2,optional,list<string>" json:"group_ids,omitempty"`
}

func NewListBotGroupsResp() *ListBotGroupsResp {
	return &ListBotGroupsResp{}
}

func (p *ListBotGroupsResp) InitDefault() {
}

var ListBotGroupsResp_Base_DEFAULT *common.BaseResp

func (p *ListBotGroupsResp) GetBase() (v *common.BaseResp) {
	if !p.IsSetBase() {
		return ListBotGroupsResp_Base_DEFAULT
	}
	return p.Base
}

var ListBotGroupsResp_GroupIds_DEFAULT []string

func (p *ListBotGroupsResp) GetGroupIds() (v []string) {
	if !p.IsSetGroupIds() {
		return ListBotGroupsResp_GroupIds_DEFAULT
	}
	return p.GroupIds
}
func (p *ListBotGroupsResp) SetBase(val *common.BaseResp) {
	p.Base = val
}
func (p *ListBotGroupsResp) SetGroupIds(val []string) {
	p.GroupIds = val
}

func (p *ListBotGroupsResp) IsSetBase() bool {
	return p.Base != nil
}

func (p *ListBotGroupsResp) IsSetGroupIds() bool {
	return p.GroupIds != nil
}

func (p *ListBotGroupsResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ListBotGroupsResp(%+v)", *p)
}

var fieldIDToName_ListBotGroupsResp = map[int16]string{
	1: "base",
	2: "group_ids",
}

type RegisterMCPServerReq struct {
	ServerName      string  `thrift:"server_name,1,required" frugal:"1,required,string" json:"server_name"`
	ServerUrl       string  `thrift:"server_url,2,required" frugal:"2,required,string" json:"server_url"`
	AuthToken       *string `thrift:"auth_token,3,optional" frugal:"3,optional,string" json:"auth_token,omitempty"`
	SyncIntervalSec *int32  `thrift:"sync_interval_sec,4,optional" frugal:"4,optional,i32" json:"sync_interval_sec,omitempty"`
}

func NewRegisterMCPServerReq() *RegisterMCPServerReq {
	return &RegisterMCPServerReq{}
}

func (p *RegisterMCPServerReq) InitDefault() {
}

func (p *RegisterMCPServerReq) GetServerName() (v string) {
	return p.ServerName
}

func (p *RegisterMCPServerReq) GetServerUrl() (v string) {
	return p.ServerUrl
}

var RegisterMCPServerReq_AuthToken_DEFAULT string

func (p *RegisterMCPServerReq) GetAuthToken() (v string) {
	if !p.IsSetAuthToken() {
		return RegisterMCPServerReq_AuthToken_DEFAULT
	}
	return *p.AuthToken
}

var RegisterMCPServerReq_SyncIntervalSec_DEFAULT int32

func (p *RegisterMCPServerReq) GetSyncIntervalSec() (v int32) {
	if !p.IsSetSyncIntervalSec() {
		return RegisterMCPServerReq_SyncIntervalSec_DEFAULT
	}
	return *p.SyncIntervalSec
}
func (p *RegisterMCPServerReq) SetServerName(val string) {
	p.ServerName = val
}
func (p *RegisterMCPServerReq) SetServerUrl(val string) {
	p.ServerUrl = val
}
func (p *RegisterMCPServerReq) SetAuthToken(val *string) {
	p.AuthToken = val
}
func (p *RegisterMCPServerReq) SetSyncIntervalSec(val *int32) {
	p.SyncIntervalSec = val
}

func (p *RegisterMCPServerReq) IsSetAuthToken() bool {
	return p.AuthToken != nil
}

func (p *RegisterMCPServerReq) IsSetSyncIntervalSec() bool {
	return p.SyncIntervalSec != nil
}

func (p *RegisterMCPServerReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RegisterMCPServerReq(%+v)", *p)
}

var fieldIDToName_RegisterMCPServerReq = map[int16]string{
	1: "server_name",
	2: "server_url",
	3: "auth_token",
	4: "sync_interval_sec",
}

type RegisterMCPServerResp struct {
	Base   *common.BaseResp      `thrift:"base,1,required" frugal:"1,required,common.BaseResp" json:"base"`
	Server *common.MCPServerInfo `thrift:"server,2,optional" frugal:"2,optional,common.MCPServerInfo" json:"server,omitempty"`
	Tools  []*common.MCPToolInfo `thrift:"tools,3,optional" frugal:"3,optional,list<common.MCPToolInfo>" json:"tools,omitempty"`
}

func NewRegisterMCPServerResp() *RegisterMCPServerResp {
	return &RegisterMCPServerResp{}
}

func (p *RegisterMCPServerResp) InitDefault() {
}

var RegisterMCPServerResp_Base_DEFAULT *common.BaseResp

func (p *RegisterMCPServerResp) GetBase() (v *common.BaseResp) {
	if !p.IsSetBase() {
		return RegisterMCPServerResp_Base_DEFAULT
	}
	return p.Base
}

var RegisterMCPServerResp_Server_DEFAULT *common.MCPServerInfo

func (p *RegisterMCPServerResp) GetServer() (v *common.MCPServerInfo) {
	if !p.IsSetServer() {
		return RegisterMCPServerResp_Server_DEFAULT
	}
	return p.Server
}

var RegisterMCPServerResp_Tools_DEFAULT []*common.MCPToolInfo

func (p *RegisterMCPServerResp) GetTools() (v []*common.MCPToolInfo) {
	if !p.IsSetTools() {
		return RegisterMCPServerResp_Tools_DEFAULT
	}
	return p.Tools
}
func (p *RegisterMCPServerResp) SetBase(val *common.BaseResp) {
	p.Base = val
}
func (p *RegisterMCPServerResp) SetServer(val *common.MCPServerInfo) {
	p.Server = val
}
func (p *RegisterMCPServerResp) SetTools(val []*common.MCPToolInfo) {
	p.Tools = val
}

func (p *RegisterMCPServerResp) IsSetBase() bool {
	return p.Base != nil
}

func (p *RegisterMCPServerResp) IsSetServer() bool {
	return p.Server != nil
}

func (p *RegisterMCPServerResp) IsSetTools() bool {
	return p.Tools != nil
}

func (p *RegisterMCPServerResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RegisterMCPServerResp(%+v)", *p)
}

var fieldIDToName_RegisterMCPServerResp = map[int16]string{
	1: "base",
	2: "server",
	3: "tools",
}

type RefreshMCPServerReq struct {
	ServerId int64 `thrift:"server_id,1,required" frugal:"1,required,i64" json:"server_id"`
}

func NewRefreshMCPServerReq() *RefreshMCPServerReq {
	return &RefreshMCPServerReq{}
}

func (p *RefreshMCPServerReq) InitDefault() {
}

func (p *RefreshMCPServerReq) GetServerId() (v int64) {
	return p.ServerId
}
func (p *RefreshMCPServerReq) SetServerId(val int64) {
	p.ServerId = val
}

func (p *RefreshMCPServerReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RefreshMCPServerReq(%+v)", *p)
}

var fieldIDToName_RefreshMCPServerReq = map[int16]string{
	1: "server_id",
}

type RefreshMCPServerResp struct {
	Base  *common.BaseResp      `thrift:"base,1,required" frugal:"1,required,common.BaseResp" json:"base"`
	Tools []*common.MCPToolInfo `thrift:"tools,2,optional" frugal:"2,optional,list<common.MCPToolInfo>" json:"tools,omitempty"`
}

func NewRefreshMCPServerResp() *RefreshMCPServerResp {
	return &RefreshMCPServerResp{}
}

func (p *RefreshMCPServerResp) InitDefault() {
}

var RefreshMCPServerResp_Base_DEFAULT *common.BaseResp

func (p *RefreshMCPServerResp) GetBase() (v *common.BaseResp) {
	if !p.IsSetBase() {
		return RefreshMCPServerResp_Base_DEFAULT
	}
	return p.Base
}

var RefreshMCPServerResp_Tools_DEFAULT []*common.MCPToolInfo

func (p *RefreshMCPServerResp) GetTools() (v []*common.MCPToolInfo) {
	if !p.IsSetTools() {
		return RefreshMCPServerResp_Tools_DEFAULT
	}
	return p.Tools
}
func (p *RefreshMCPServerResp) SetBase(val *common.BaseResp) {
	p.Base = val
}
func (p *RefreshMCPServerResp) SetTools(val []*common.MCPToolInfo) {
	p.Tools = val
}

func (p *RefreshMCPServerResp) IsSetBase() bool {
	return p.Base != nil
}

func (p *RefreshMCPServerResp) IsSetTools() bool {
	return p.Tools != nil
}

func (p *RefreshMCPServerResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RefreshMCPServerResp(%+v)", *p)
}

var fieldIDToName_RefreshMCPServerResp = map[int16]string{
	1: "base",
	2: "tools",
}

type ListMCPServersReq struct {
}

func NewListMCPServersReq() *ListMCPServersReq {
	return &ListMCPServersReq{}
}

func (p *ListMCPServersReq) InitDefault() {
}

func (p *ListMCPServersReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ListMCPServersReq(%+v)", *p)
}

var fieldIDToName_ListMCPServersReq = map[int16]string{}

type MCPServerListData struct {
	Servers []*common.MCPServerInfo `thrift:"servers,1,required" frugal:"1,required,list<common.MCPServerInfo>" json:"servers"`
}

func NewMCPServerListData() *MCPServerListData {
	return &MCPServerListData{}
}

func (p *MCPServerListData) InitDefault() {
}

func (p *MCPServerListData) GetServers() (v []*common.MCPServerInfo) {
	return p.Servers
}
func (p *MCPServerListData) SetServers(val []*common.MCPServerInfo) {
	p.Servers = val
}

func (p *MCPServerListData) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MCPServerListData(%+v)", *p)
}

var fieldIDToName_MCPServerListData = map[int16]string{
	1: "servers",
}

type ListMCPServersResp struct {
	Base *common.BaseResp   `thrift:"base,1,required" frugal:"1,required,common.BaseResp" json:"base"`
	Data *MCPServerListData `thrift:"data,2,optional" frugal:"2,optional,MCPServerListData" json:"data,omitempty"`
}

func NewListMCPServersResp() *ListMCPServersResp {
	return &ListMCPServersResp{}
}

func (p *ListMCPServersResp) InitDefault() {
}

var ListMCPServersResp_Base_DEFAULT *common.BaseResp

func (p *ListMCPServersResp) GetBase() (v *common.BaseResp) {
	if !p.IsSetBase() {
		return ListMCPServersResp_Base_DEFAULT
	}
	return p.Base
}

var ListMCPServersResp_Data_DEFAULT *MCPServerListData

func (p *ListMCPServersResp) GetData() (v *MCPServerListData) {
	if !p.IsSetData() {
		return ListMCPServersResp_Data_DEFAULT
	}
	return p.Data
}
func (p *ListMCPServersResp) SetBase(val *common.BaseResp) {
	p.Base = val
}
func (p *ListMCPServersResp) SetData(val *MCPServerListData) {
	p.Data = val
}

func (p *ListMCPServersResp) IsSetBase() bool {
	return p.Base != nil
}

func (p *ListMCPServersResp) IsSetData() bool {
	return p.Data != nil
}

func (p *ListMCPServersResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ListMCPServersResp(%+v)", *p)
}

var fieldIDToName_ListMCPServersResp = map[int16]string{
	1: "base",
	2: "data",
}

type DeleteMCPServerReq struct {
	ServerId int64 `thrift:"server_id,1,required" frugal:"1,required,i64" json:"server_id"`
}

func NewDeleteMCPServerReq() *DeleteMCPServerReq {
	return &DeleteMCPServerReq{}
}

func (p *DeleteMCPServerReq) InitDefault() {
}

func (p *DeleteMCPServerReq) GetServerId() (v int64) {
	return p.ServerId
}
func (p *DeleteMCPServerReq) SetServerId(val int64) {
	p.ServerId = val
}

func (p *DeleteMCPServerReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DeleteMCPServerReq(%+v)", *p)
}

var fieldIDToName_DeleteMCPServerReq = map[int16]string{
	1: "server_id",
}

type DeleteMCPServerResp struct {
	Base *common.BaseResp `thrift:"base,1,required" frugal:"1,required,common.BaseResp" json:"base"`
}

func NewDeleteMCPServerResp() *DeleteMCPServerResp {
	return &DeleteMCPServerResp{}
}

func (p *DeleteMCPServerResp) InitDefault() {
}

var DeleteMCPServerResp_Base_DEFAULT *common.BaseResp

func (p *DeleteMCPServerResp) GetBase() (v *common.BaseResp) {
	if !p.IsSetBase() {
		return DeleteMCPServerResp_Base_DEFAULT
	}
	return p.Base
}
func (p *DeleteMCPServerResp) SetBase(val *common.BaseResp) {
	p.Base = val
}

func (p *DeleteMCPServerResp) IsSetBase() bool {
	return p.Base != nil
}

func (p *DeleteMCPServerResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DeleteMCPServerResp(%+v)", *p)
}

var fieldIDToName_DeleteMCPServerResp = map[int16]string{
	1: "base",
}

type ListToolsReq struct {
}

func NewListToolsReq() *ListToolsReq {
	return &ListToolsReq{}
}

func (p *ListToolsReq) InitDefault() {
}

func (p *ListToolsReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ListToolsReq(%+v)", *p)
}

var fieldIDToName_ListToolsReq = map[int16]string{}

type ToolListData struct {
	Tools []*common.MCPToolInfo `thrift:"tools,1,required" frugal:"1,required,list<common.MCPToolInfo>" json:"tools"`
}

func NewToolListData() *ToolListData {
	return &ToolListData{}
}

func (p *ToolListData) InitDefault() {
}

func (p *ToolListData) GetTools() (v []*common.MCPToolInfo) {
	return p.Tools
}
func (p *ToolListData) SetTools(val []*common.MCPToolInfo) {
	p.Tools = val
}

func (p *ToolListData) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ToolListData(%+v)", *p)
}

var fieldIDToName_ToolListData = map[int16]string{
	1: "tools",
}

type ListToolsResp struct {
	Base *common.BaseResp `thrift:"base,1,required" frugal:"1,required,common.BaseResp" json:"base"`
	Data *ToolListData    `thrift:"data,2,optional" frugal:"2,optional,ToolListData" json:"data,omitempty"`
}

func NewListToolsResp() *ListToolsResp {
	return &ListToolsResp{}
}

func (p *ListToolsResp) InitDefault() {
}

var ListToolsResp_Base_DEFAULT *common.BaseResp

func (p *ListToolsResp) GetBase() (v *common.BaseResp) {
	if !p.IsSetBase() {
		return ListToolsResp_Base_DEFAULT
	}
	return p.Base
}

var ListToolsResp_Data_DEFAULT *ToolListData

func (p *ListToolsResp) GetData() (v *ToolListData) {
	if !p.IsSetData() {
		return ListToolsResp_Data_DEFAULT
	}
	return p.Data
}
func (p *ListToolsResp) SetBase(val *common.BaseResp) {
	p.Base = val
}
func (p *ListToolsResp) SetData(val *ToolListData) {
	p.Data = val
}

func (p *ListToolsResp) IsSetBase() bool {
	return p.Base != nil
}

func (p *ListToolsResp) IsSetData() bool {
	return p.Data != nil
}

func (p *ListToolsResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ListToolsResp(%+v)", *p)
}

var fieldIDToName_ListToolsResp = map[int16]string{
	1: "base",
	2: "data",
}

type CredentialInfo struct {
	CredentialId string `thrift:"credential_id,1,required" frugal:"1,required,string" json:"credential_id"`
	ServiceName  string `thrift:"service_name,2,required" frugal:"2,required,string" json:"service_name"`
	Username     string `thrift:"username,3,required" frugal:"3,required,string" json:"username"`
	SavedAt      string `thrift:"saved_at,4,required" frugal:"4,required,string" json:"saved_at"`
}

func NewCredentialInfo() *CredentialInfo {
	return &CredentialInfo{}
}

func (p *CredentialInfo) InitDefault() {
}

func (p *CredentialInfo) GetCredentialId() (v string) {
	return p.CredentialId
}

func (p *CredentialInfo) GetServiceName() (v string) {
	return p.ServiceName
}

func (p *CredentialInfo) GetUsername() (v string) {
	return p.Username
}

func (p *CredentialInfo) GetSavedAt() (v string) {
	return p.SavedAt
}
func (p *CredentialInfo) SetCredentialId(val string) {
	p.CredentialId = val
}
func (p *CredentialInfo) SetServiceName(val string) {
	p.ServiceName = val
}
func (p *CredentialInfo) SetUsername(val string) {
	p.Username = val
}
func (p *CredentialInfo) SetSavedAt(val string) {
	p.SavedAt = val
}

func (p *CredentialInfo) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CredentialInfo(%+v)", *p)
}

var fieldIDToName_CredentialInfo = map[int16]string{
	1: "credential_id",
	2: "service_name",
	3: "username",
	4: "saved_at",
}

type SaveCredentialReq struct {
	ServiceName string `thrift:"service_name,1,required" frugal:"1,required,string" json:"service_name"`
	Username    string `thrift:"username,2,required" frugal:"2,required,string" json:"username"`
	Password    string `thrift:"password,3,required" frugal:"3,required,string" json:"password"`
}

func NewSaveCredentialReq() *SaveCredentialReq {
	return &SaveCredentialReq{}
}

func (p *SaveCredentialReq) InitDefault() {
}

func (p *SaveCredentialReq) GetServiceName() (v string) {
	return p.ServiceName
}

func (p *SaveCredentialReq) GetUsername() (v string) {
	return p.Username
}

func (p *SaveCredentialReq) GetPassword() (v string) {
	return p.Password
}
func (p *SaveCredentialReq) SetServiceName(val string) {
	p.ServiceName = val
}
func (p *SaveCredentialReq) SetUsername(val string) {
	p.Username = val
}
func (p *SaveCredentialReq) SetPassword(val string) {
	p.Password = val
}

func (p *SaveCredentialReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SaveCredentialReq(%+v)", *p)
}

var fieldIDToName_SaveCredentialReq = map[int16]string{
	1: "service_name",
	2: "username",
	3: "password",
}

type SaveCredentialResp struct {
	Base       *common.BaseResp `thrift:"base,1,required" frugal:"1,required,common.BaseResp" json:"base"`
	Credential *CredentialInfo  `thrift:"credential,2,optional" frugal:"2,optional,CredentialInfo" json:"credential,omitempty"`
}

func NewSaveCredentialResp() *SaveCredentialResp {
	return &SaveCredentialResp{}
}

func (p *SaveCredentialResp) InitDefault() {
}

var SaveCredentialResp_Base_DEFAULT *common.BaseResp

func (p *SaveCredentialResp) GetBase() (v *common.BaseResp) {
	if !p.IsSetBase() {
		return SaveCredentialResp_Base_DEFAULT
	}
	return p.Base
}

var SaveCredentialResp_Credential_DEFAULT *CredentialInfo

func (p *SaveCredentialResp) GetCredential() (v *CredentialInfo) {
	if !p.IsSetCredential() {
		return SaveCredentialResp_Credential_DEFAULT
	}
	return p.Credential
}
func (p *SaveCredentialResp) SetBase(val *common.BaseResp) {
	p.Base = val
}
func (p *SaveCredentialResp) SetCredential(val *CredentialInfo) {
	p.Credential = val
}

func (p *SaveCredentialResp) IsSetBase() bool {
	return p.Base != nil
}

func (p *SaveCredentialResp) IsSetCredential() bool {
	return p.Credential != nil
}

func (p *SaveCredentialResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SaveCredentialResp(%+v)", *p)
}

var fieldIDToName_SaveCredentialResp = map[int16]string{
	1: "base",
	2: "credential",
}

type DeleteCredentialReq struct {
	CredentialId string `thrift:"credential_id,1,required" frugal:"1,required,string" json:"credential_id"`
}

func NewDeleteCredentialReq() *DeleteCredentialReq {
	return &DeleteCredentialReq{}
}

func (p *DeleteCredentialReq) InitDefault() {
}

func (p *DeleteCredentialReq) GetCredentialId() (v string) {
	return p.CredentialId
}
func (p *DeleteCredentialReq) SetCredentialId(val string) {
	p.CredentialId = val
}

func (p *DeleteCredentialReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DeleteCredentialReq(%+v)", *p)
}

var fieldIDToName_DeleteCredentialReq = map[int16]string{
	1: "credential_id",
}

type DeleteCredentialResp struct {
	Base *common.BaseResp `thrift:"base,1,required" frugal:"1,required,common.BaseResp" json:"base"`
}

func NewDeleteCredentialResp() *DeleteCredentialResp {
	return &DeleteCredentialResp{}
}

func (p *DeleteCredentialResp) InitDefault() {
}

var DeleteCredentialResp_Base_DEFAULT *common.BaseResp

func (p *DeleteCredentialResp) GetBase() (v *common.BaseResp) {
	if !p.IsSetBase() {
		return DeleteCredentialResp_Base_DEFAULT
	}
	return p.Base
}
func (p *DeleteCredentialResp) SetBase(val *common.BaseResp) {
	p.Base = val
}

func (p *DeleteCredentialResp) IsSetBase() bool {
	return p.Base != nil
}

func (p *DeleteCredentialResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DeleteCredentialResp(%+v)", *p)
}

var fieldIDToName_DeleteCredentialResp = map[int16]string{
	1: "base",
}

type ListCredentialsReq struct {
	ServiceName *string `thrift:"service_name,1,optional" frugal:"1,optional,string" json:"service_name,omitempty"`
}

func NewListCredentialsReq() *ListCredentialsReq {
	return &ListCredentialsReq{}
}

func (p *ListCredentialsReq) InitDefault() {
}

var ListCredentialsReq_ServiceName_DEFAULT string

func (p *ListCredentialsReq) GetServiceName() (v string) {
	if !p.IsSetServiceName() {
		return ListCredentialsReq_ServiceName_DEFAULT
	}
	return *p.ServiceName
}
func (p *ListCredentialsReq) SetServiceName(val *string) {
	p.ServiceName = val
}

func (p *ListCredentialsReq) IsSetServiceName() bool {
	return p.ServiceName != nil
}

func (p *ListCredentialsReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ListCredentialsReq(%+v)", *p)
}

var fieldIDToName_ListCredentialsReq = map[int16]string{
	1: "service_name",
}

type CredentialListData struct {
	Credentials []*CredentialInfo `thrift:"credentials,1,required" frugal:"1,required,list<CredentialInfo>" json:"credentials"`
}

func NewCredentialListData() *CredentialListData {
	return &CredentialListData{}
}

func (p *CredentialListData) InitDefault() {
}

func (p *CredentialListData) GetCredentials() (v []*CredentialInfo) {
	return p.Credentials
}
func (p *CredentialListData) SetCredentials(val []*CredentialInfo) {
	p.Credentials = val
}

func (p *CredentialListData) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CredentialListData(%+v)", *p)
}

var fieldIDToName_CredentialListData = map[int16]string{
	1: "credentials",
}

type ListCredentialsResp struct {
	Base *common.BaseResp    `thrift:"base,1,required" frugal:"1,required,common.BaseResp" json:"base"`
	Data *CredentialListData `thrift:"data,2,optional" frugal:"2,optional,CredentialListData" json:"data,omitempty"`
}

func NewListCredentialsResp() *ListCredentialsResp {
	return &ListCredentialsResp{}
}

func (p *ListCredentialsResp) InitDefault() {
}

var ListCredentialsResp_Base_DEFAULT *common.BaseResp

func (p *ListCredentialsResp) GetBase() (v *common.BaseResp) {
	if !p.IsSetBase() {
		return ListCredentialsResp_Base_DEFAULT
	}
	return p.Base
}

var ListCredentialsResp_Data_DEFAULT *CredentialListData

func (p *ListCredentialsResp) GetData() (v *CredentialListData) {
	if !p.IsSetData() {
		return ListCredentialsResp_Data_DEFAULT
	}
	return p.Data
}
func (p *ListCredentialsResp) SetBase(val *common.BaseResp) {
	p.Base = val
}
func (p *ListCredentialsResp) SetData(val *CredentialListData) {
	p.Data = val
}

func (p *ListCredentialsResp) IsSetBase() bool {
	return p.Base != nil
}

func (p *ListCredentialsResp) IsSetData() bool {
	return p.Data != nil
}

func (p *ListCredentialsResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ListCredentialsResp(%+v)", *p)
}

var fieldIDToName_ListCredentialsResp = map[int16]string{
	1: "base",
	2: "data",
}

type AIService interface {
	ProcessMessage(ctx context.Context, req *ProcessMessageReq) (r *ProcessMessageResp, err error)

	CreateBot(ctx context.Context, req *CreateBotReq) (r *CreateBotResp, err error)

	UpdateBot(ctx context.Context, req *UpdateBotReq) (r *UpdateBotResp, err error)

	ListBots(ctx context.Context, req *ListBotsReq) (r *ListBotsResp, err error)

	GetBot(ctx context.Context, req *GetBotReq) (r *GetBotResp, err error)

	DeleteBot(ctx context.Context, req *DeleteBotReq) (r *DeleteBotResp, err error)

	AddBotToGroup(ctx context.Context, req *AddBotToGroupReq) (r *AddBotToGroupResp, err error)

	RemoveBotFromGroup(ctx context.Context, req *RemoveBotFromGroupReq) (r *RemoveBotFromGroupResp, err error)

	ListGroupBots(ctx context.Context, req *ListGroupBotsReq) (r *ListGroupBotsResp, err error)

	ListBotGroups(ctx context.Context, req *ListBotGroupsReq) (r *ListBotGroupsResp, err error)

	RegisterMCPServer(ctx context.Context, req *RegisterMCPServerReq) (r *RegisterMCPServerResp, err error)

	RefreshMCPServer(ctx context.Context, req *RefreshMCPServerReq) (r *RefreshMCPServerResp, err error)

	ListMCPServers(ctx context.Context, req *ListMCPServersReq) (r *ListMCPServersResp, err error)

	DeleteMCPServer(ctx context.Context, req *DeleteMCPServerReq) (r *DeleteMCPServerResp, err error)

	ListTools(ctx context.Context, req *ListToolsReq) (r *ListToolsResp, err error)

	SaveCredential(ctx context.Context, req *SaveCredentialReq) (r *SaveCredentialResp, err error)

	DeleteCredential(ctx context.Context, req *DeleteCredentialReq) (r *DeleteCredentialResp, err error)

	ListCredentials(ctx context.Context, req *ListCredentialsReq) (r *ListCredentialsResp, err error)
}

type AIServiceProcessMessageArgs struct {
	Req *ProcessMessageReq `thrift:"req,1,required" frugal:"1,required,ProcessMessageReq" json:"req"`
}

func NewAIServiceProcessMessageArgs() *AIServiceProcessMessageArgs {
	return &AIServiceProcessMessageArgs{}
}

func (p *AIServiceProcessMessageArgs) InitDefault() {
}

var AIServiceProcessMessageArgs_Req_DEFAULT *ProcessMessageReq

func (p *AIServiceProcessMessageArgs) GetReq() (v *ProcessMessageReq) {
	if !p.IsSetReq() {
		return AIServiceProcessMessageArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *AIServiceProcessMessageArgs) SetReq(val *ProcessMessageReq) {
	p.Req = val
}

func (p *AIServiceProcessMessageArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *AIServiceProcessMessageArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AIServiceProcessMessageArgs(%+v)", *p)
}

var fieldIDToName_AIServiceProcessMessageArgs = map[int16]string{
	1: "req",
}

type AIServiceProcessMessageResult struct {
	Success *ProcessMessageResp `thrift:"success,0,optional" frugal:"0,optional,ProcessMessageResp" json:"success,omitempty"`
}

func NewAIServiceProcessMessageResult() *AIServiceProcessMessageResult {
	return &AIServiceProcessMessageResult{}
}

func (p *AIServiceProcessMessageResult) InitDefault() {
}

var AIServiceProcessMessageResult_Success_DEFAULT *ProcessMessageResp

func (p *AIServiceProcessMessageResult) GetSuccess() (v *ProcessMessageResp) {
	if !p.IsSetSuccess() {
		return AIServiceProcessMessageResult_Success_DEFAULT
	}
	return p.Success
}
func (p *AIServiceProcessMessageResult) SetSuccess(x interface{}) {
	p.Success = x.(*ProcessMessageResp)
}

func (p *AIServiceProcessMessageResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *AIServiceProcessMessageResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AIServiceProcessMessageResult(%+v)", *p)
}

var fieldIDToName_AIServiceProcessMessageResult = map[int16]string{
	0: "success",
}

type AIServiceCreateBotArgs struct {
	Req *CreateBotReq `thrift:"req,1,required" frugal:"1,required,CreateBotReq" json:"req"`
}

func NewAIServiceCreateBotArgs() *AIServiceCreateBotArgs {
	return &AIServiceCreateBotArgs{}
}

func (p *AIServiceCreateBotArgs) InitDefault() {
}

var AIServiceCreateBotArgs_Req_DEFAULT *CreateBotReq

func (p *AIServiceCreateBotArgs) GetReq() (v *CreateBotReq) {
	if !p.IsSetReq() {
		return AIServiceCreateBotArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *AIServiceCreateBotArgs) SetReq(val *CreateBotReq) {
	p.Req = val
}

func (p *AIServiceCreateBotArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *AIServiceCreateBotArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AIServiceCreateBotArgs(%+v)", *p)
}

var fieldIDToName_AIServiceCreateBotArgs = map[int16]string{
	1: "req",
}

type AIServiceCreateBotResult struct {
	Success *CreateBotResp `thrift:"success,0,optional" frugal:"0,optional,CreateBotResp" json:"success,omitempty"`
}

func NewAIServiceCreateBotResult() *AIServiceCreateBotResult {
	return &AIServiceCreateBotResult{}
}

func (p *AIServiceCreateBotResult) InitDefault() {
}

var AIServiceCreateBotResult_Success_DEFAULT *CreateBotResp

func (p *AIServiceCreateBotResult) GetSuccess() (v *CreateBotResp) {
	if !p.IsSetSuccess() {
		return AIServiceCreateBotResult_Success_DEFAULT
	}
	return p.Success
}
func (p *AIServiceCreateBotResult) SetSuccess(x interface{}) {
	p.Success = x.(*CreateBotResp)
}

func (p *AIServiceCreateBotResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *AIServiceCreateBotResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AIServiceCreateBotResult(%+v)", *p)
}

var fieldIDToName_AIServiceCreateBotResult = map[int16]string{
	0: "success",
}

type AIServiceUpdateBotArgs struct {
	Req *UpdateBotReq `thrift:"req,1,required" frugal:"1,required,UpdateBotReq" json:"req"`
}

func NewAIServiceUpdateBotArgs() *AIServiceUpdateBotArgs {
	return &AIServiceUpdateBotArgs{}
}

func (p *AIServiceUpdateBotArgs) InitDefault() {
}

var AIServiceUpdateBotArgs_Req_DEFAULT *UpdateBotReq

func (p *AIServiceUpdateBotArgs) GetReq() (v *UpdateBotReq) {
	if !p.IsSetReq() {
		return AIServiceUpdateBotArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *AIServiceUpdateBotArgs) SetReq(val *UpdateBotReq) {
	p.Req = val
}

func (p *AIServiceUpdateBotArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *AIServiceUpdateBotArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AIServiceUpdateBotArgs(%+v)", *p)
}

var fieldIDToName_AIServiceUpdateBotArgs = map[int16]string{
	1: "req",
}

type AIServiceUpdateBotResult struct {
	Success *UpdateBotResp `thrift:"success,0,optional" frugal:"0,optional,UpdateBotResp" json:"success,omitempty"`
}

func NewAIServiceUpdateBotResult() *AIServiceUpdateBotResult {
	return &AIServiceUpdateBotResult{}
}

func (p *AIServiceUpdateBotResult) InitDefault() {
}

var AIServiceUpdateBotResult_Success_DEFAULT *UpdateBotResp

func (p *AIServiceUpdateBotResult) GetSuccess() (v *UpdateBotResp) {
	if !p.IsSetSuccess() {
		return AIServiceUpdateBotResult_Success_DEFAULT
	}
	return p.Success
}
func (p *AIServiceUpdateBotResult) SetSuccess(x interface{}) {
	p.Success = x.(*UpdateBotResp)
}

func (p *AIServiceUpdateBotResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *AIServiceUpdateBotResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AIServiceUpdateBotResult(%+v)", *p)
}

var fieldIDToName_AIServiceUpdateBotResult = map[int16]string{
	0: "success",
}

type AIServiceListBotsArgs struct {
	Req *ListBotsReq `thrift:"req,1,required" frugal:"1,required,ListBotsReq" json:"req"`
}

func NewAIServiceListBotsArgs() *AIServiceListBotsArgs {
	return &AIServiceListBotsArgs{}
}

func (p *AIServiceListBotsArgs) InitDefault() {
}

var AIServiceListBotsArgs_Req_DEFAULT *ListBotsReq

func (p *AIServiceListBotsArgs) GetReq() (v *ListBotsReq) {
	if !p.IsSetReq() {
		return AIServiceListBotsArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *AIServiceListBotsArgs) SetReq(val *ListBotsReq) {
	p.Req = val
}

func (p *AIServiceListBotsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *AIServiceListBotsArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AIServiceListBotsArgs(%+v)", *p)
}

var fieldIDToName_AIServiceListBotsArgs = map[int16]string{
	1: "req",
}

type AIServiceListBotsResult struct {
	Success *ListBotsResp `thrift:"success,0,optional" frugal:"0,optional,ListBotsResp" json:"success,omitempty"`
}

func NewAIServiceListBotsResult() *AIServiceListBotsResult {
	return &AIServiceListBotsResult{}
}

func (p *AIServiceListBotsResult) InitDefault() {
}

var AIServiceListBotsResult_Success_DEFAULT *ListBotsResp

func (p *AIServiceListBotsResult) GetSuccess() (v *ListBotsResp) {
	if !p.IsSetSuccess() {
		return AIServiceListBotsResult_Success_DEFAULT
	}
	return p.Success
}
func (p *AIServiceListBotsResult) SetSuccess(x interface{}) {
	p.Success = x.(*ListBotsResp)
}

func (p *AIServiceListBotsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *AIServiceListBotsResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AIServiceListBotsResult(%+v)", *p)
}

var fieldIDToName_AIServiceListBotsResult = map[int16]string{
	0: "success",
}

type AIServiceGetBotArgs struct {
	Req *GetBotReq `thrift:"req,1,required" frugal:"1,required,GetBotReq" json:"req"`
}

func NewAIServiceGetBotArgs() *AIServiceGetBotArgs {
	return &AIServiceGetBotArgs{}
}

func (p *AIServiceGetBotArgs) InitDefault() {
}

var AIServiceGetBotArgs_Req_DEFAULT *GetBotReq

func (p *AIServiceGetBotArgs) GetReq() (v *GetBotReq) {
	if !p.IsSetReq() {
		return AIServiceGetBotArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *AIServiceGetBotArgs) SetReq(val *GetBotReq) {
	p.Req = val
}

func (p *AIServiceGetBotArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *AIServiceGetBotArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AIServiceGetBotArgs(%+v)", *p)
}

var fieldIDToName_AIServiceGetBotArgs = map[int16]string{
	1: "req",
}

type AIServiceGetBotResult struct {
	Success *GetBotResp `thrift:"success,0,optional" frugal:"0,optional,GetBotResp" json:"success,omitempty"`
}

func NewAIServiceGetBotResult() *AIServiceGetBotResult {
	return &AIServiceGetBotResult{}
}

func (p *AIServiceGetBotResult) InitDefault() {
}

var AIServiceGetBotResult_Success_DEFAULT *GetBotResp

func (p *AIServiceGetBotResult) GetSuccess() (v *GetBotResp) {
	if !p.IsSetSuccess() {
		return AIServiceGetBotResult_Success_DEFAULT
	}
	return p.Success
}
func (p *AIServiceGetBotResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetBotResp)
}

func (p *AIServiceGetBotResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *AIServiceGetBotResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AIServiceGetBotResult(%+v)", *p)
}

var fieldIDToName_AIServiceGetBotResult = map[int16]string{
	0: "success",
}

type AIServiceDeleteBotArgs struct {
	Req *DeleteBotReq `thrift:"req,1,required" frugal:"1,required,DeleteBotReq" json:"req"`
}

func NewAIServiceDeleteBotArgs() *AIServiceDeleteBotArgs {
	return &AIServiceDeleteBotArgs{}
}

func (p *AIServiceDeleteBotArgs) InitDefault() {
}

var AIServiceDeleteBotArgs_Req_DEFAULT *DeleteBotReq

func (p *AIServiceDeleteBotArgs) GetReq() (v *DeleteBotReq) {
	if !p.IsSetReq() {
		return AIServiceDeleteBotArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *AIServiceDeleteBotArgs) SetReq(val *DeleteBotReq) {
	p.Req = val
}

func (p *AIServiceDeleteBotArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *AIServiceDeleteBotArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AIServiceDeleteBotArgs(%+v)", *p)
}

var fieldIDToName_AIServiceDeleteBotArgs = map[int16]string{
	1: "req",
}

type AIServiceDeleteBotResult struct {
	Success *DeleteBotResp `thrift:"success,0,optional" frugal:"0,optional,DeleteBotResp" json:"success,omitempty"`
}

func NewAIServiceDeleteBotResult() *AIServiceDeleteBotResult {
	return &AIServiceDeleteBotResult{}
}

func (p *AIServiceDeleteBotResult) InitDefault() {
}

var AIServiceDeleteBotResult_Success_DEFAULT *DeleteBotResp

func (p *AIServiceDeleteBotResult) GetSuccess() (v *DeleteBotResp) {
	if !p.IsSetSuccess() {
		return AIServiceDeleteBotResult_Success_DEFAULT
	}
	return p.Success
}
func (p *AIServiceDeleteBotResult) SetSuccess(x interface{}) {
	p.Success = x.(*DeleteBotResp)
}

func (p *AIServiceDeleteBotResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *AIServiceDeleteBotResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AIServiceDeleteBotResult(%+v)", *p)
}

var fieldIDToName_AIServiceDeleteBotResult = map[int16]string{
	0: "success",
}

type AIServiceAddBotToGroupArgs struct {
	Req *AddBotToGroupReq `thrift:"req,1,required" frugal:"1,required,AddBotToGroupReq" json:"req"`
}

func NewAIServiceAddBotToGroupArgs() *AIServiceAddBotToGroupArgs {
	return &AIServiceAddBotToGroupArgs{}
}

func (p *AIServiceAddBotToGroupArgs) InitDefault() {
}

var AIServiceAddBotToGroupArgs_Req_DEFAULT *AddBotToGroupReq

func (p *AIServiceAddBotToGroupArgs) GetReq() (v *AddBotToGroupReq) {
	if !p.IsSetReq() {
		return AIServiceAddBotToGroupArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *AIServiceAddBotToGroupArgs) SetReq(val *AddBotToGroupReq) {
	p.Req = val
}

func (p *AIServiceAddBotToGroupArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *AIServiceAddBotToGroupArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AIServiceAddBotToGroupArgs(%+v)", *p)
}

var fieldIDToName_AIServiceAddBotToGroupArgs = map[int16]string{
	1: "req",
}

type AIServiceAddBotToGroupResult struct {
	Success *AddBotToGroupResp `thrift:"success,0,optional" frugal:"0,optional,AddBotToGroupResp" json:"success,omitempty"`
}

func NewAIServiceAddBotToGroupResult() *AIServiceAddBotToGroupResult {
	return &AIServiceAddBotToGroupResult{}
}

func (p *AIServiceAddBotToGroupResult) InitDefault() {
}

var AIServiceAddBotToGroupResult_Success_DEFAULT *AddBotToGroupResp

func (p *AIServiceAddBotToGroupResult) GetSuccess() (v *AddBotToGroupResp) {
	if !p.IsSetSuccess() {
		return AIServiceAddBotToGroupResult_Success_DEFAULT
	}
	return p.Success
}
func (p *AIServiceAddBotToGroupResult) SetSuccess(x interface{}) {
	p.Success = x.(*AddBotToGroupResp)
}

func (p *AIServiceAddBotToGroupResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *AIServiceAddBotToGroupResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AIServiceAddBotToGroupResult(%+v)", *p)
}

var fieldIDToName_AIServiceAddBotToGroupResult = map[int16]string{
	0: "success",
}

type AIServiceRemoveBotFromGroupArgs struct {
	Req *RemoveBotFromGroupReq `thrift:"req,1,required" frugal:"1,required,RemoveBotFromGroupReq" json:"req"`
}

func NewAIServiceRemoveBotFromGroupArgs() *AIServiceRemoveBotFromGroupArgs {
	return &AIServiceRemoveBotFromGroupArgs{}
}

func (p *AIServiceRemoveBotFromGroupArgs) InitDefault() {
}

var AIServiceRemoveBotFromGroupArgs_Req_DEFAULT *RemoveBotFromGroupReq

func (p *AIServiceRemoveBotFromGroupArgs) GetReq() (v *RemoveBotFromGroupReq) {
	if !p.IsSetReq() {
		return AIServiceRemoveBotFromGroupArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *AIServiceRemoveBotFromGroupArgs) SetReq(val *RemoveBotFromGroupReq) {
	p.Req = val
}

func (p *AIServiceRemoveBotFromGroupArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *AIServiceRemoveBotFromGroupArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AIServiceRemoveBotFromGroupArgs(%+v)", *p)
}

var fieldIDToName_AIServiceRemoveBotFromGroupArgs = map[int16]string{
	1: "req",
}

type AIServiceRemoveBotFromGroupResult struct {
	Success *RemoveBotFromGroupResp `thrift:"success,0,optional" frugal:"0,optional,RemoveBotFromGroupResp" json:"success,omitempty"`
}

func NewAIServiceRemoveBotFromGroupResult() *AIServiceRemoveBotFromGroupResult {
	return &AIServiceRemoveBotFromGroupResult{}
}

func (p *AIServiceRemoveBotFromGroupResult) InitDefault() {
}

var AIServiceRemoveBotFromGroupResult_Success_DEFAULT *RemoveBotFromGroupResp

func (p *AIServiceRemoveBotFromGroupResult) GetSuccess() (v *RemoveBotFromGroupResp) {
	if !p.IsSetSuccess() {
		return AIServiceRemoveBotFromGroupResult_Success_DEFAULT
	}
	return p.Success
}
func (p *AIServiceRemoveBotFromGroupResult) SetSuccess(x interface{}) {
	p.Success = x.(*RemoveBotFromGroupResp)
}

func (p *AIServiceRemoveBotFromGroupResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *AIServiceRemoveBotFromGroupResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AIServiceRemoveBotFromGroupResult(%+v)", *p)
}

var fieldIDToName_AIServiceRemoveBotFromGroupResult = map[int16]string{
	0: "success",
}

type AIServiceListGroupBotsArgs struct {
	Req *ListGroupBotsReq `thrift:"req,1,required" frugal:"1,required,ListGroupBotsReq" json:"req"`
}

func NewAIServiceListGroupBotsArgs() *AIServiceListGroupBotsArgs {
	return &AIServiceListGroupBotsArgs{}
}

func (p *AIServiceListGroupBotsArgs) InitDefault() {
}

var AIServiceListGroupBotsArgs_Req_DEFAULT *ListGroupBotsReq

func (p *AIServiceListGroupBotsArgs) GetReq() (v *ListGroupBotsReq) {
	if !p.IsSetReq() {
		return AIServiceListGroupBotsArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *AIServiceListGroupBotsArgs) SetReq(val *ListGroupBotsReq) {
	p.Req = val
}

func (p *AIServiceListGroupBotsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *AIServiceListGroupBotsArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AIServiceListGroupBotsArgs(%+v)", *p)
}

var fieldIDToName_AIServiceListGroupBotsArgs = map[int16]string{
	1: "req",
}

type AIServiceListGroupBotsResult struct {
	Success *ListGroupBotsResp `thrift:"success,0,optional" frugal:"0,optional,ListGroupBotsResp" json:"success,omitempty"`
}

func NewAIServiceListGroupBotsResult() *AIServiceListGroupBotsResult {
	return &AIServiceListGroupBotsResult{}
}

func (p *AIServiceListGroupBotsResult) InitDefault() {
}

var AIServiceListGroupBotsResult_Success_DEFAULT *ListGroupBotsResp

func (p *AIServiceListGroupBotsResult) GetSuccess() (v *ListGroupBotsResp) {
	if !p.IsSetSuccess() {
		return AIServiceListGroupBotsResult_Success_DEFAULT
	}
	return p.Success
}
func (p *AIServiceListGroupBotsResult) SetSuccess(x interface{}) {
	p.Success = x.(*ListGroupBotsResp)
}

func (p *AIServiceListGroupBotsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *AIServiceListGroupBotsResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AIServiceListGroupBotsResult(%+v)", *p)
}

var fieldIDToName_AIServiceListGroupBotsResult = map[int16]string{
	0: "success",
}

type AIServiceListBotGroupsArgs struct {
	Req *ListBotGroupsReq `thrift:"req,1,required" frugal:"1,required,ListBotGroupsReq" json:"req"`
}

func NewAIServiceListBotGroupsArgs() *AIServiceListBotGroupsArgs {
	return &AIServiceListBotGroupsArgs{}
}

func (p *AIServiceListBotGroupsArgs) InitDefault() {
}

var AIServiceListBotGroupsArgs_Req_DEFAULT *ListBotGroupsReq

func (p *AIServiceListBotGroupsArgs) GetReq() (v *ListBotGroupsReq) {
	if !p.IsSetReq() {
		return AIServiceListBotGroupsArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *AIServiceListBotGroupsArgs) SetReq(val *ListBotGroupsReq) {
	p.Req = val
}

func (p *AIServiceListBotGroupsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *AIServiceListBotGroupsArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AIServiceListBotGroupsArgs(%+v)", *p)
}

var fieldIDToName_AIServiceListBotGroupsArgs = map[int16]string{
	1: "req",
}

type AIServiceListBotGroupsResult struct {
	Success *ListBotGroupsResp `thrift:"success,0,optional" frugal:"0,optional,ListBotGroupsResp" json:"success,omitempty"`
}

func NewAIServiceListBotGroupsResult() *AIServiceListBotGroupsResult {
	return &AIServiceListBotGroupsResult{}
}

func (p *AIServiceListBotGroupsResult) InitDefault() {
}

var AIServiceListBotGroupsResult_Success_DEFAULT *ListBotGroupsResp

func (p *AIServiceListBotGroupsResult) GetSuccess() (v *ListBotGroupsResp) {
	if !p.IsSetSuccess() {
		return AIServiceListBotGroupsResult_Success_DEFAULT
	}
	return p.Success
}
func (p *AIServiceListBotGroupsResult) SetSuccess(x interface{}) {
	p.Success = x.(*ListBotGroupsResp)
}

func (p *AIServiceListBotGroupsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *AIServiceListBotGroupsResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AIServiceListBotGroupsResult(%+v)", *p)
}

var fieldIDToName_AIServiceListBotGroupsResult = map[int16]string{
	0: "success",
}

type AIServiceRegisterMCPServerArgs struct {
	Req *RegisterMCPServerReq `thrift:"req,1,required" frugal:"1,required,RegisterMCPServerReq" json:"req"`
}

func NewAIServiceRegisterMCPServerArgs() *AIServiceRegisterMCPServerArgs {
	return &AIServiceRegisterMCPServerArgs{}
}

func (p *AIServiceRegisterMCPServerArgs) InitDefault() {
}

var AIServiceRegisterMCPServerArgs_Req_DEFAULT *RegisterMCPServerReq

func (p *AIServiceRegisterMCPServerArgs) GetReq() (v *RegisterMCPServerReq) {
	if !p.IsSetReq() {
		return AIServiceRegisterMCPServerArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *AIServiceRegisterMCPServerArgs) SetReq(val *RegisterMCPServerReq) {
	p.Req = val
}

func (p *AIServiceRegisterMCPServerArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *AIServiceRegisterMCPServerArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AIServiceRegisterMCPServerArgs(%+v)", *p)
}

var fieldIDToName_AIServiceRegisterMCPServerArgs = map[int16]string{
	1: "req",
}

type AIServiceRegisterMCPServerResult struct {
	Success *RegisterMCPServerResp `thrift:"success,0,optional" frugal:"0,optional,RegisterMCPServerResp" json:"success,omitempty"`
}

func NewAIServiceRegisterMCPServerResult() *AIServiceRegisterMCPServerResult {
	return &AIServiceRegisterMCPServerResult{}
}

func (p *AIServiceRegisterMCPServerResult) InitDefault() {
}

var AIServiceRegisterMCPServerResult_Success_DEFAULT *RegisterMCPServerResp

func (p *AIServiceRegisterMCPServerResult) GetSuccess() (v *RegisterMCPServerResp) {
	if !p.IsSetSuccess() {
		return AIServiceRegisterMCPServerResult_Success_DEFAULT
	}
	return p.Success
}
func (p *AIServiceRegisterMCPServerResult) SetSuccess(x interface{}) {
	p.Success = x.(*RegisterMCPServerResp)
}

func (p *AIServiceRegisterMCPServerResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *AIServiceRegisterMCPServerResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AIServiceRegisterMCPServerResult(%+v)", *p)
}

var fieldIDToName_AIServiceRegisterMCPServerResult = map[int16]string{
	0: "success",
}

type AIServiceRefreshMCPServerArgs struct {
	Req *RefreshMCPServerReq `thrift:"req,1,required" frugal:"1,required,RefreshMCPServerReq" json:"req"`
}

func NewAIServiceRefreshMCPServerArgs() *AIServiceRefreshMCPServerArgs {
	return &AIServiceRefreshMCPServerArgs{}
}

func (p *AIServiceRefreshMCPServerArgs) InitDefault() {
}

var AIServiceRefreshMCPServerArgs_Req_DEFAULT *RefreshMCPServerReq

func (p *AIServiceRefreshMCPServerArgs) GetReq() (v *RefreshMCPServerReq) {
	if !p.IsSetReq() {
		return AIServiceRefreshMCPServerArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *AIServiceRefreshMCPServerArgs) SetReq(val *RefreshMCPServerReq) {
	p.Req = val
}

func (p *AIServiceRefreshMCPServerArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *AIServiceRefreshMCPServerArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AIServiceRefreshMCPServerArgs(%+v)", *p)
}

var fieldIDToName_AIServiceRefreshMCPServerArgs = map[int16]string{
	1: "req",
}

type AIServiceRefreshMCPServerResult struct {
	Success *RefreshMCPServerResp `thrift:"success,0,optional" frugal:"0,optional,RefreshMCPServerResp" json:"success,omitempty"`
}

func NewAIServiceRefreshMCPServerResult() *AIServiceRefreshMCPServerResult {
	return &AIServiceRefreshMCPServerResult{}
}

func (p *AIServiceRefreshMCPServerResult) InitDefault() {
}

var AIServiceRefreshMCPServerResult_Success_DEFAULT *RefreshMCPServerResp

func (p *AIServiceRefreshMCPServerResult) GetSuccess() (v *RefreshMCPServerResp) {
	if !p.IsSetSuccess() {
		return AIServiceRefreshMCPServerResult_Success_DEFAULT
	}
	return p.Success
}
func (p *AIServiceRefreshMCPServerResult) SetSuccess(x interface{}) {
	p.Success = x.(*RefreshMCPServerResp)
}

func (p *AIServiceRefreshMCPServerResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *AIServiceRefreshMCPServerResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AIServiceRefreshMCPServerResult(%+v)", *p)
}

var fieldIDToName_AIServiceRefreshMCPServerResult = map[int16]string{
	0: "success",
}

type AIServiceListMCPServersArgs struct {
	Req *ListMCPServersReq `thrift:"req,1,required" frugal:"1,required,ListMCPServersReq" json:"req"`
}

func NewAIServiceListMCPServersArgs() *AIServiceListMCPServersArgs {
	return &AIServiceListMCPServersArgs{}
}

func (p *AIServiceListMCPServersArgs) InitDefault() {
}

var AIServiceListMCPServersArgs_Req_DEFAULT *ListMCPServersReq

func (p *AIServiceListMCPServersArgs) GetReq() (v *ListMCPServersReq) {
	if !p.IsSetReq() {
		return AIServiceListMCPServersArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *AIServiceListMCPServersArgs) SetReq(val *ListMCPServersReq) {
	p.Req = val
}

func (p *AIServiceListMCPServersArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *AIServiceListMCPServersArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AIServiceListMCPServersArgs(%+v)", *p)
}

var fieldIDToName_AIServiceListMCPServersArgs = map[int16]string{
	1: "req",
}

type AIServiceListMCPServersResult struct {
	Success *ListMCPServersResp `thrift:"success,0,optional" frugal:"0,optional,ListMCPServersResp" json:"success,omitempty"`
}

func NewAIServiceListMCPServersResult() *AIServiceListMCPServersResult {
	return &AIServiceListMCPServersResult{}
}

func (p *AIServiceListMCPServersResult) InitDefault() {
}

var AIServiceListMCPServersResult_Success_DEFAULT *ListMCPServersResp

func (p *AIServiceListMCPServersResult) GetSuccess() (v *ListMCPServersResp) {
	if !p.IsSetSuccess() {
		return AIServiceListMCPServersResult_Success_DEFAULT
	}
	return p.Success
}
func (p *AIServiceListMCPServersResult) SetSuccess(x interface{}) {
	p.Success = x.(*ListMCPServersResp)
}

func (p *AIServiceListMCPServersResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *AIServiceListMCPServersResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AIServiceListMCPServersResult(%+v)", *p)
}

var fieldIDToName_AIServiceListMCPServersResult = map[int16]string{
	0: "success",
}

type AIServiceDeleteMCPServerArgs struct {
	Req *DeleteMCPServerReq `thrift:"req,1,required" frugal:"1,required,DeleteMCPServerReq" json:"req"`
}

func NewAIServiceDeleteMCPServerArgs() *AIServiceDeleteMCPServerArgs {
	return &AIServiceDeleteMCPServerArgs{}
}

func (p *AIServiceDeleteMCPServerArgs) InitDefault() {
}

var AIServiceDeleteMCPServerArgs_Req_DEFAULT *DeleteMCPServerReq

func (p *AIServiceDeleteMCPServerArgs) GetReq() (v *DeleteMCPServerReq) {
	if !p.IsSetReq() {
		return AIServiceDeleteMCPServerArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *AIServiceDeleteMCPServerArgs) SetReq(val *DeleteMCPServerReq) {
	p.Req = val
}

func (p *AIServiceDeleteMCPServerArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *AIServiceDeleteMCPServerArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AIServiceDeleteMCPServerArgs(%+v)", *p)
}

var fieldIDToName_AIServiceDeleteMCPServerArgs = map[int16]string{
	1: "req",
}

type AIServiceDeleteMCPServerResult struct {
	Success *DeleteMCPServerResp `thrift:"success,0,optional" frugal:"0,optional,DeleteMCPServerResp" json:"success,omitempty"`
}

func NewAIServiceDeleteMCPServerResult() *AIServiceDeleteMCPServerResult {
	return &AIServiceDeleteMCPServerResult{}
}

func (p *AIServiceDeleteMCPServerResult) InitDefault() {
}

var AIServiceDeleteMCPServerResult_Success_DEFAULT *DeleteMCPServerResp

func (p *AIServiceDeleteMCPServerResult) GetSuccess() (v *DeleteMCPServerResp) {
	if !p.IsSetSuccess() {
		return AIServiceDeleteMCPServerResult_Success_DEFAULT
	}
	return p.Success
}
func (p *AIServiceDeleteMCPServerResult) SetSuccess(x interface{}) {
	p.Success = x.(*DeleteMCPServerResp)
}

func (p *AIServiceDeleteMCPServerResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *AIServiceDeleteMCPServerResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AIServiceDeleteMCPServerResult(%+v)", *p)
}

var fieldIDToName_AIServiceDeleteMCPServerResult = map[int16]string{
	0: "success",
}

type AIServiceListToolsArgs struct {
	Req *ListToolsReq `thrift:"req,1,required" frugal:"1,required,ListToolsReq" json:"req"`
}

func NewAIServiceListToolsArgs() *AIServiceListToolsArgs {
	return &AIServiceListToolsArgs{}
}

func (p *AIServiceListToolsArgs) InitDefault() {
}

var AIServiceListToolsArgs_Req_DEFAULT *ListToolsReq

func (p *AIServiceListToolsArgs) GetReq() (v *ListToolsReq) {
	if !p.IsSetReq() {
		return AIServiceListToolsArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *AIServiceListToolsArgs) SetReq(val *ListToolsReq) {
	p.Req = val
}

func (p *AIServiceListToolsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *AIServiceListToolsArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AIServiceListToolsArgs(%+v)", *p)
}

var fieldIDToName_AIServiceListToolsArgs = map[int16]string{
	1: "req",
}

type AIServiceListToolsResult struct {
	Success *ListToolsResp `thrift:"success,0,optional" frugal:"0,optional,ListToolsResp" json:"success,omitempty"`
}

func NewAIServiceListToolsResult() *AIServiceListToolsResult {
	return &AIServiceListToolsResult{}
}

func (p *AIServiceListToolsResult) InitDefault() {
}

var AIServiceListToolsResult_Success_DEFAULT *ListToolsResp

func (p *AIServiceListToolsResult) GetSuccess() (v *ListToolsResp) {
	if !p.IsSetSuccess() {
		return AIServiceListToolsResult_Success_DEFAULT
	}
	return p.Success
}
func (p *AIServiceListToolsResult) SetSuccess(x interface{}) {
	p.Success = x.(*ListToolsResp)
}

func (p *AIServiceListToolsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *AIServiceListToolsResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AIServiceListToolsResult(%+v)", *p)
}

var fieldIDToName_AIServiceListToolsResult = map[int16]string{
	0: "success",
}

type AIServiceSaveCredentialArgs struct {
	Req *SaveCredentialReq `thrift:"req,1,required" frugal:"1,required,SaveCredentialReq" json:"req"`
}

func NewAIServiceSaveCredentialArgs() *AIServiceSaveCredentialArgs {
	return &AIServiceSaveCredentialArgs{}
}

func (p *AIServiceSaveCredentialArgs) InitDefault() {
}

var AIServiceSaveCredentialArgs_Req_DEFAULT *SaveCredentialReq

func (p *AIServiceSaveCredentialArgs) GetReq() (v *SaveCredentialReq) {
	if !p.IsSetReq() {
		return AIServiceSaveCredentialArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *AIServiceSaveCredentialArgs) SetReq(val *SaveCredentialReq) {
	p.Req = val
}

func (p *AIServiceSaveCredentialArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *AIServiceSaveCredentialArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AIServiceSaveCredentialArgs(%+v)", *p)
}

var fieldIDToName_AIServiceSaveCredentialArgs = map[int16]string{
	1: "req",
}

type AIServiceSaveCredentialResult struct {
	Success *SaveCredentialResp `thrift:"success,0,optional" frugal:"0,optional,SaveCredentialResp" json:"success,omitempty"`
}

func NewAIServiceSaveCredentialResult() *AIServiceSaveCredentialResult {
	return &AIServiceSaveCredentialResult{}
}

func (p *AIServiceSaveCredentialResult) InitDefault() {
}

var AIServiceSaveCredentialResult_Success_DEFAULT *SaveCredentialResp

func (p *AIServiceSaveCredentialResult) GetSuccess() (v *SaveCredentialResp) {
	if !p.IsSetSuccess() {
		return AIServiceSaveCredentialResult_Success_DEFAULT
	}
	return p.Success
}
func (p *AIServiceSaveCredentialResult) SetSuccess(x interface{}) {
	p.Success = x.(*SaveCredentialResp)
}

func (p *AIServiceSaveCredentialResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *AIServiceSaveCredentialResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AIServiceSaveCredentialResult(%+v)", *p)
}

var fieldIDToName_AIServiceSaveCredentialResult = map[int16]string{
	0: "success",
}

type AIServiceDeleteCredentialArgs struct {
	Req *DeleteCredentialReq `thrift:"req,1,required" frugal:"1,required,DeleteCredentialReq" json:"req"`
}

func NewAIServiceDeleteCredentialArgs() *AIServiceDeleteCredentialArgs {
	return &AIServiceDeleteCredentialArgs{}
}

func (p *AIServiceDeleteCredentialArgs) InitDefault() {
}

var AIServiceDeleteCredentialArgs_Req_DEFAULT *DeleteCredentialReq

func (p *AIServiceDeleteCredentialArgs) GetReq() (v *DeleteCredentialReq) {
	if !p.IsSetReq() {
		return AIServiceDeleteCredentialArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *AIServiceDeleteCredentialArgs) SetReq(val *DeleteCredentialReq) {
	p.Req = val
}

func (p *AIServiceDeleteCredentialArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *AIServiceDeleteCredentialArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AIServiceDeleteCredentialArgs(%+v)", *p)
}

var fieldIDToName_AIServiceDeleteCredentialArgs = map[int16]string{
	1: "req",
}

type AIServiceDeleteCredentialResult struct {
	Success *DeleteCredentialResp `thrift:"success,0,optional" frugal:"0,optional,DeleteCredentialResp" json:"success,omitempty"`
}

func NewAIServiceDeleteCredentialResult() *AIServiceDeleteCredentialResult {
	return &AIServiceDeleteCredentialResult{}
}

func (p *AIServiceDeleteCredentialResult) InitDefault() {
}

var AIServiceDeleteCredentialResult_Success_DEFAULT *DeleteCredentialResp

func (p *AIServiceDeleteCredentialResult) GetSuccess() (v *DeleteCredentialResp) {
	if !p.IsSetSuccess() {
		return AIServiceDeleteCredentialResult_Success_DEFAULT
	}
	return p.Success
}
func (p *AIServiceDeleteCredentialResult) SetSuccess(x interface{}) {
	p.Success = x.(*DeleteCredentialResp)
}

func (p *AIServiceDeleteCredentialResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *AIServiceDeleteCredentialResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AIServiceDeleteCredentialResult(%+v)", *p)
}

var fieldIDToName_AIServiceDeleteCredentialResult = map[int16]string{
	0: "success",
}

type AIServiceListCredentialsArgs struct {
	Req *ListCredentialsReq `thrift:"req,1,required" frugal:"1,required,ListCredentialsReq" json:"req"`
}

func NewAIServiceListCredentialsArgs() *AIServiceListCredentialsArgs {
	return &AIServiceListCredentialsArgs{}
}

func (p *AIServiceListCredentialsArgs) InitDefault() {
}

var AIServiceListCredentialsArgs_Req_DEFAULT *ListCredentialsReq

func (p *AIServiceListCredentialsArgs) GetReq() (v *ListCredentialsReq) {
	if !p.IsSetReq() {
		return AIServiceListCredentialsArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *AIServiceListCredentialsArgs) SetReq(val *ListCredentialsReq) {
	p.Req = val
}

func (p *AIServiceListCredentialsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *AIServiceListCredentialsArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AIServiceListCredentialsArgs(%+v)", *p)
}

var fieldIDToName_AIServiceListCredentialsArgs = map[int16]string{
	1: "req",
}

type AIServiceListCredentialsResult struct {
	Success *ListCredentialsResp `thrift:"success,0,optional" frugal:"0,optional,ListCredentialsResp" json:"success,omitempty"`
}

func NewAIServiceListCredentialsResult() *AIServiceListCredentialsResult {
	return &AIServiceListCredentialsResult{}
}

func (p *AIServiceListCredentialsResult) InitDefault() {
}

var AIServiceListCredentialsResult_Success_DEFAULT *ListCredentialsResp

func (p *AIServiceListCredentialsResult) GetSuccess() (v *ListCredentialsResp) {
	if !p.IsSetSuccess() {
		return AIServiceListCredentialsResult_Success_DEFAULT
	}
	return p.Success
}
func (p *AIServiceListCredentialsResult) SetSuccess(x interface{}) {
	p.Success = x.(*ListCredentialsResp)
}

func (p *AIServiceListCredentialsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *AIServiceListCredentialsResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AIServiceListCredentialsResult(%+v)", *p)
}

var fieldIDToName_AIServiceListCredentialsResult = map[int16]string{
	0: "success",
}
