// Code generated by Kitex v0.16.2. DO NOT EDIT.

package aiservice

import (
	ai "StreamCore/kitex_gen/ai"
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"ProcessMessage": kitex.NewMethodInfo(
		processMessageHandler,
		newAIServiceProcessMessageArgs,
		newAIServiceProcessMessageResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"CreateBot": kitex.NewMethodInfo(
		createBotHandler,
		newAIServiceCreateBotArgs,
		newAIServiceCreateBotResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"UpdateBot": kitex.NewMethodInfo(
		updateBotHandler,
		newAIServiceUpdateBotArgs,
		newAIServiceUpdateBotResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ListBots": kitex.NewMethodInfo(
		listBotsHandler,
		newAIServiceListBotsArgs,
		newAIServiceListBotsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetBot": kitex.NewMethodInfo(
		getBotHandler,
		newAIServiceGetBotArgs,
		newAIServiceGetBotResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"DeleteBot": kitex.NewMethodInfo(
		deleteBotHandler,
		newAIServiceDeleteBotArgs,
		newAIServiceDeleteBotResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"AddBotToGroup": kitex.NewMethodInfo(
		addBotToGroupHandler,
		newAIServiceAddBotToGroupArgs,
		newAIServiceAddBotToGroupResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"RemoveBotFromGroup": kitex.NewMethodInfo(
		removeBotFromGroupHandler,
		newAIServiceRemoveBotFromGroupArgs,
		newAIServiceRemoveBotFromGroupResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ListGroupBots": kitex.NewMethodInfo(
		listGroupBotsHandler,
		newAIServiceListGroupBotsArgs,
		newAIServiceListGroupBotsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ListBotGroups": kitex.NewMethodInfo(
		listBotGroupsHandler,
		newAIServiceListBotGroupsArgs,
		newAIServiceListBotGroupsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"RegisterMCPServer": kitex.NewMethodInfo(
		registerMCPServerHandler,
		newAIServiceRegisterMCPServerArgs,
		newAIServiceRegisterMCPServerResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"RefreshMCPServer": kitex.NewMethodInfo(
		refreshMCPServerHandler,
		newAIServiceRefreshMCPServerArgs,
		newAIServiceRefreshMCPServerResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ListMCPServers": kitex.NewMethodInfo(
		listMCPServersHandler,
		newAIServiceListMCPServersArgs,
		newAIServiceListMCPServersResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"DeleteMCPServer": kitex.NewMethodInfo(
		deleteMCPServerHandler,
		newAIServiceDeleteMCPServerArgs,
		newAIServiceDeleteMCPServerResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ListTools": kitex.NewMethodInfo(
		listToolsHandler,
		newAIServiceListToolsArgs,
		newAIServiceListToolsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"SaveCredential": kitex.NewMethodInfo(
		saveCredentialHandler,
		newAIServiceSaveCredentialArgs,
		newAIServiceSaveCredentialResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"DeleteCredential": kitex.NewMethodInfo(
		deleteCredentialHandler,
		newAIServiceDeleteCredentialArgs,
		newAIServiceDeleteCredentialResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ListCredentials": kitex.NewMethodInfo(
		listCredentialsHandler,
		newAIServiceListCredentialsArgs,
		newAIServiceListCredentialsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	aIServiceServiceInfo                = NewServiceInfo()
	aIServiceServiceInfoForClient       = NewServiceInfoForClient()
	aIServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return aIServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return aIServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return aIServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "AIService"
	handlerType := (*ai.AIService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "ai",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.16.2",
		Extra:           extra,
	}
	return svcInfo
}

func processMessageHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*ai.AIServiceProcessMessageArgs)
	realResult := result.(*ai.AIServiceProcessMessageResult)
	success, err := handler.(ai.AIService).ProcessMessage(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newAIServiceProcessMessageArgs() interface{} {
	return ai.NewAIServiceProcessMessageArgs()
}

func newAIServiceProcessMessageResult() interface{} {
	return ai.NewAIServiceProcessMessageResult()
}

func createBotHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*ai.AIServiceCreateBotArgs)
	realResult := result.(*ai.AIServiceCreateBotResult)
	success, err := handler.(ai.AIService).CreateBot(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newAIServiceCreateBotArgs() interface{} {
	return ai.NewAIServiceCreateBotArgs()
}

func newAIServiceCreateBotResult() interface{} {
	return ai.NewAIServiceCreateBotResult()
}

func updateBotHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*ai.AIServiceUpdateBotArgs)
	realResult := result.(*ai.AIServiceUpdateBotResult)
	success, err := handler.(ai.AIService).UpdateBot(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newAIServiceUpdateBotArgs() interface{} {
	return ai.NewAIServiceUpdateBotArgs()
}

func newAIServiceUpdateBotResult() interface{} {
	return ai.NewAIServiceUpdateBotResult()
}

func listBotsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*ai.AIServiceListBotsArgs)
	realResult := result.(*ai.AIServiceListBotsResult)
	success, err := handler.(ai.AIService).ListBots(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newAIServiceListBotsArgs() interface{} {
	return ai.NewAIServiceListBotsArgs()
}

func newAIServiceListBotsResult() interface{} {
	return ai.NewAIServiceListBotsResult()
}

func getBotHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*ai.AIServiceGetBotArgs)
	realResult := result.(*ai.AIServiceGetBotResult)
	success, err := handler.(ai.AIService).GetBot(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newAIServiceGetBotArgs() interface{} {
	return ai.NewAIServiceGetBotArgs()
}

func newAIServiceGetBotResult() interface{} {
	return ai.NewAIServiceGetBotResult()
}

func deleteBotHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*ai.AIServiceDeleteBotArgs)
	realResult := result.(*ai.AIServiceDeleteBotResult)
	success, err := handler.(ai.AIService).DeleteBot(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newAIServiceDeleteBotArgs() interface{} {
	return ai.NewAIServiceDeleteBotArgs()
}

func newAIServiceDeleteBotResult() interface{} {
	return ai.NewAIServiceDeleteBotResult()
}

func addBotToGroupHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*ai.AIServiceAddBotToGroupArgs)
	realResult := result.(*ai.AIServiceAddBotToGroupResult)
	success, err := handler.(ai.AIService).AddBotToGroup(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newAIServiceAddBotToGroupArgs() interface{} {
	return ai.NewAIServiceAddBotToGroupArgs()
}

func newAIServiceAddBotToGroupResult() interface{} {
	return ai.NewAIServiceAddBotToGroupResult()
}

func removeBotFromGroupHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*ai.AIServiceRemoveBotFromGroupArgs)
	realResult := result.(*ai.AIServiceRemoveBotFromGroupResult)
	success, err := handler.(ai.AIService).RemoveBotFromGroup(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newAIServiceRemoveBotFromGroupArgs() interface{} {
	return ai.NewAIServiceRemoveBotFromGroupArgs()
}

func newAIServiceRemoveBotFromGroupResult() interface{} {
	return ai.NewAIServiceRemoveBotFromGroupResult()
}

func listGroupBotsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*ai.AIServiceListGroupBotsArgs)
	realResult := result.(*ai.AIServiceListGroupBotsResult)
	success, err := handler.(ai.AIService).ListGroupBots(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newAIServiceListGroupBotsArgs() interface{} {
	return ai.NewAIServiceListGroupBotsArgs()
}

func newAIServiceListGroupBotsResult() interface{} {
	return ai.NewAIServiceListGroupBotsResult()
}

func listBotGroupsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*ai.AIServiceListBotGroupsArgs)
	realResult := result.(*ai.AIServiceListBotGroupsResult)
	success, err := handler.(ai.AIService).ListBotGroups(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newAIServiceListBotGroupsArgs() interface{} {
	return ai.NewAIServiceListBotGroupsArgs()
}

func newAIServiceListBotGroupsResult() interface{} {
	return ai.NewAIServiceListBotGroupsResult()
}

func registerMCPServerHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*ai.AIServiceRegisterMCPServerArgs)
	realResult := result.(*ai.AIServiceRegisterMCPServerResult)
	success, err := handler.(ai.AIService).RegisterMCPServer(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newAIServiceRegisterMCPServerArgs() interface{} {
	return ai.NewAIServiceRegisterMCPServerArgs()
}

func newAIServiceRegisterMCPServerResult() interface{} {
	return ai.NewAIServiceRegisterMCPServerResult()
}

func refreshMCPServerHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*ai.AIServiceRefreshMCPServerArgs)
	realResult := result.(*ai.AIServiceRefreshMCPServerResult)
	success, err := handler.(ai.AIService).RefreshMCPServer(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newAIServiceRefreshMCPServerArgs() interface{} {
	return ai.NewAIServiceRefreshMCPServerArgs()
}

func newAIServiceRefreshMCPServerResult() interface{} {
	return ai.NewAIServiceRefreshMCPServerResult()
}

func listMCPServersHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*ai.AIServiceListMCPServersArgs)
	realResult := result.(*ai.AIServiceListMCPServersResult)
	success, err := handler.(ai.AIService).ListMCPServers(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newAIServiceListMCPServersArgs() interface{} {
	return ai.NewAIServiceListMCPServersArgs()
}

func newAIServiceListMCPServersResult() interface{} {
	return ai.NewAIServiceListMCPServersResult()
}

func deleteMCPServerHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*ai.AIServiceDeleteMCPServerArgs)
	realResult := result.(*ai.AIServiceDeleteMCPServerResult)
	success, err := handler.(ai.AIService).DeleteMCPServer(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newAIServiceDeleteMCPServerArgs() interface{} {
	return ai.NewAIServiceDeleteMCPServerArgs()
}

func newAIServiceDeleteMCPServerResult() interface{} {
	return ai.NewAIServiceDeleteMCPServerResult()
}

func listToolsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*ai.AIServiceListToolsArgs)
	realResult := result.(*ai.AIServiceListToolsResult)
	success, err := handler.(ai.AIService).ListTools(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newAIServiceListToolsArgs() interface{} {
	return ai.NewAIServiceListToolsArgs()
}

func newAIServiceListToolsResult() interface{} {
	return ai.NewAIServiceListToolsResult()
}

func saveCredentialHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*ai.AIServiceSaveCredentialArgs)
	realResult := result.(*ai.AIServiceSaveCredentialResult)
	success, err := handler.(ai.AIService).SaveCredential(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newAIServiceSaveCredentialArgs() interface{} {
	return ai.NewAIServiceSaveCredentialArgs()
}

func newAIServiceSaveCredentialResult() interface{} {
	return ai.NewAIServiceSaveCredentialResult()
}

func deleteCredentialHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*ai.AIServiceDeleteCredentialArgs)
	realResult := result.(*ai.AIServiceDeleteCredentialResult)
	success, err := handler.(ai.AIService).DeleteCredential(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newAIServiceDeleteCredentialArgs() interface{} {
	return ai.NewAIServiceDeleteCredentialArgs()
}

func newAIServiceDeleteCredentialResult() interface{} {
	return ai.NewAIServiceDeleteCredentialResult()
}

func listCredentialsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*ai.AIServiceListCredentialsArgs)
	realResult := result.(*ai.AIServiceListCredentialsResult)
	success, err := handler.(ai.AIService).ListCredentials(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newAIServiceListCredentialsArgs() interface{} {
	return ai.NewAIServiceListCredentialsArgs()
}

func newAIServiceListCredentialsResult() interface{} {
	return ai.NewAIServiceListCredentialsResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) ProcessMessage(ctx context.Context, req *ai.ProcessMessageReq) (r *ai.ProcessMessageResp, err error) {
	var _args ai.AIServiceProcessMessageArgs
	_args.Req = req
	var _result ai.AIServiceProcessMessageResult
	if err = p.c.Call(ctx, "ProcessMessage", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CreateBot(ctx context.Context, req *ai.CreateBotReq) (r *ai.CreateBotResp, err error) {
	var _args ai.AIServiceCreateBotArgs
	_args.Req = req
	var _result ai.AIServiceCreateBotResult
	if err = p.c.Call(ctx, "CreateBot", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UpdateBot(ctx context.Context, req *ai.UpdateBotReq) (r *ai.UpdateBotResp, err error) {
	var _args ai.AIServiceUpdateBotArgs
	_args.Req = req
	var _result ai.AIServiceUpdateBotResult
	if err = p.c.Call(ctx, "UpdateBot", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListBots(ctx context.Context, req *ai.ListBotsReq) (r *ai.ListBotsResp, err error) {
	var _args ai.AIServiceListBotsArgs
	_args.Req = req
	var _result ai.AIServiceListBotsResult
	if err = p.c.Call(ctx, "ListBots", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetBot(ctx context.Context, req *ai.GetBotReq) (r *ai.GetBotResp, err error) {
	var _args ai.AIServiceGetBotArgs
	_args.Req = req
	var _result ai.AIServiceGetBotResult
	if err = p.c.Call(ctx, "GetBot", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DeleteBot(ctx context.Context, req *ai.DeleteBotReq) (r *ai.DeleteBotResp, err error) {
	var _args ai.AIServiceDeleteBotArgs
	_args.Req = req
	var _result ai.AIServiceDeleteBotResult
	if err = p.c.Call(ctx, "DeleteBot", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) AddBotToGroup(ctx context.Context, req *ai.AddBotToGroupReq) (r *ai.AddBotToGroupResp, err error) {
	var _args ai.AIServiceAddBotToGroupArgs
	_args.Req = req
	var _result ai.AIServiceAddBotToGroupResult
	if err = p.c.Call(ctx, "AddBotToGroup", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) RemoveBotFromGroup(ctx context.Context, req *ai.RemoveBotFromGroupReq) (r *ai.RemoveBotFromGroupResp, err error) {
	var _args ai.AIServiceRemoveBotFromGroupArgs
	_args.Req = req
	var _result ai.AIServiceRemoveBotFromGroupResult
	if err = p.c.Call(ctx, "RemoveBotFromGroup", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListGroupBots(ctx context.Context, req *ai.ListGroupBotsReq) (r *ai.ListGroupBotsResp, err error) {
	var _args ai.AIServiceListGroupBotsArgs
	_args.Req = req
	var _result ai.AIServiceListGroupBotsResult
	if err = p.c.Call(ctx, "ListGroupBots", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListBotGroups(ctx context.Context, req *ai.ListBotGroupsReq) (r *ai.ListBotGroupsResp, err error) {
	var _args ai.AIServiceListBotGroupsArgs
	_args.Req = req
	var _result ai.AIServiceListBotGroupsResult
	if err = p.c.Call(ctx, "ListBotGroups", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) RegisterMCPServer(ctx context.Context, req *ai.RegisterMCPServerReq) (r *ai.RegisterMCPServerResp, err error) {
	var _args ai.AIServiceRegisterMCPServerArgs
	_args.Req = req
	var _result ai.AIServiceRegisterMCPServerResult
	if err = p.c.Call(ctx, "RegisterMCPServer", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) RefreshMCPServer(ctx context.Context, req *ai.RefreshMCPServerReq) (r *ai.RefreshMCPServerResp, err error) {
	var _args ai.AIServiceRefreshMCPServerArgs
	_args.Req = req
	var _result ai.AIServiceRefreshMCPServerResult
	if err = p.c.Call(ctx, "RefreshMCPServer", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListMCPServers(ctx context.Context, req *ai.ListMCPServersReq) (r *ai.ListMCPServersResp, err error) {
	var _args ai.AIServiceListMCPServersArgs
	_args.Req = req
	var _result ai.AIServiceListMCPServersResult
	if err = p.c.Call(ctx, "ListMCPServers", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DeleteMCPServer(ctx context.Context, req *ai.DeleteMCPServerReq) (r *ai.DeleteMCPServerResp, err error) {
	var _args ai.AIServiceDeleteMCPServerArgs
	_args.Req = req
	var _result ai.AIServiceDeleteMCPServerResult
	if err = p.c.Call(ctx, "DeleteMCPServer", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListTools(ctx context.Context, req *ai.ListToolsReq) (r *ai.ListToolsResp, err error) {
	var _args ai.AIServiceListToolsArgs
	_args.Req = req
	var _result ai.AIServiceListToolsResult
	if err = p.c.Call(ctx, "ListTools", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) SaveCredential(ctx context.Context, req *ai.SaveCredentialReq) (r *ai.SaveCredentialResp, err error) {
	var _args ai.AIServiceSaveCredentialArgs
	_args.Req = req
	var _result ai.AIServiceSaveCredentialResult
	if err = p.c.Call(ctx, "SaveCredential", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DeleteCredential(ctx context.Context, req *ai.DeleteCredentialReq) (r *ai.DeleteCredentialResp, err error) {
	var _args ai.AIServiceDeleteCredentialArgs
	_args.Req = req
	var _result ai.AIServiceDeleteCredentialResult
	if err = p.c.Call(ctx, "DeleteCredential", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListCredentials(ctx context.Context, req *ai.ListCredentialsReq) (r *ai.ListCredentialsResp, err error) {
	var _args ai.AIServiceListCredentialsArgs
	_args.Req = req
	var _result ai.AIServiceListCredentialsResult
	if err = p.c.Call(ctx, "ListCredentials", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
