// Code generated by Kitex v0.16.2. DO NOT EDIT.

package aiservice

import (
	ai "StreamCore/kitex_gen/ai"
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	ProcessMessage(ctx context.Context, req *ai.ProcessMessageReq, callOptions ...callopt.Option) (r *ai.ProcessMessageResp, err error)
	ProactiveCheck(ctx context.Context, req *ai.ProactiveCheckReq, callOptions ...callopt.Option) (r *ai.ProactiveCheckResp, err error)
	CreateBot(ctx context.Context, req *ai.CreateBotReq, callOptions ...callopt.Option) (r *ai.CreateBotResp, err error)
	UpdateBot(ctx context.Context, req *ai.UpdateBotReq, callOptions ...callopt.Option) (r *ai.UpdateBotResp, err error)
	ListBots(ctx context.Context, req *ai.ListBotsReq, callOptions ...callopt.Option) (r *ai.ListBotsResp, err error)
	GetBot(ctx context.Context, req *ai.GetBotReq, callOptions ...callopt.Option) (r *ai.GetBotResp, err error)
	DeleteBot(ctx context.Context, req *ai.DeleteBotReq, callOptions ...callopt.Option) (r *ai.DeleteBotResp, err error)
	AddBotToGroup(ctx context.Context, req *ai.AddBotToGroupReq, callOptions ...callopt.Option) (r *ai.AddBotToGroupResp, err error)
	RemoveBotFromGroup(ctx context.Context, req *ai.RemoveBotFromGroupReq, callOptions ...callopt.Option) (r *ai.RemoveBotFromGroupResp, err error)
	ListGroupBots(ctx context.Context, req *ai.ListGroupBotsReq, callOptions ...callopt.Option) (r *ai.ListGroupBotsResp, err error)
	ListBotGroups(ctx context.Context, req *ai.ListBotGroupsReq, callOptions ...callopt.Option) (r *ai.ListBotGroupsResp, err error)
	RegisterMCPServer(ctx context.Context, req *ai.RegisterMCPServerReq, callOptions ...callopt.Option) (r *ai.RegisterMCPServerResp, err error)
	RefreshMCPServer(ctx context.Context, req *ai.RefreshMCPServerReq, callOptions ...callopt.Option) (r *ai.RefreshMCPServerResp, err error)
	ListMCPServers(ctx context.Context, req *ai.ListMCPServersReq, callOptions ...callopt.Option) (r *ai.ListMCPServersResp, err error)
	DeleteMCPServer(ctx context.Context, req *ai.DeleteMCPServerReq, callOptions ...callopt.Option) (r *ai.DeleteMCPServerResp, err error)
	ListTools(ctx context.Context, req *ai.ListToolsReq, callOptions ...callopt.Option) (r *ai.ListToolsResp, err error)
	SaveCredential(ctx context.Context, req *ai.SaveCredentialReq, callOptions ...callopt.Option) (r *ai.SaveCredentialResp, err error)
	DeleteCredential(ctx context.Context, req *ai.DeleteCredentialReq, callOptions ...callopt.Option) (r *ai.DeleteCredentialResp, err error)
	ListCredentials(ctx context.Context, req *ai.ListCredentialsReq, callOptions ...callopt.Option) (r *ai.ListCredentialsResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kAIServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kAIServiceClient struct {
	*kClient
}

func (p *kAIServiceClient) ProcessMessage(ctx context.Context, req *ai.ProcessMessageReq, callOptions ...callopt.Option) (r *ai.ProcessMessageResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ProcessMessage(ctx, req)
}

func (p *kAIServiceClient) ProactiveCheck(ctx context.Context, req *ai.ProactiveCheckReq, callOptions ...callopt.Option) (r *ai.ProactiveCheckResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ProactiveCheck(ctx, req)
}

func (p *kAIServiceClient) CreateBot(ctx context.Context, req *ai.CreateBotReq, callOptions ...callopt.Option) (r *ai.CreateBotResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateBot(ctx, req)
}

func (p *kAIServiceClient) UpdateBot(ctx context.Context, req *ai.UpdateBotReq, callOptions ...callopt.Option) (r *ai.UpdateBotResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateBot(ctx, req)
}

func (p *kAIServiceClient) ListBots(ctx context.Context, req *ai.ListBotsReq, callOptions ...callopt.Option) (r *ai.ListBotsResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListBots(ctx, req)
}

func (p *kAIServiceClient) GetBot(ctx context.Context, req *ai.GetBotReq, callOptions ...callopt.Option) (r *ai.GetBotResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetBot(ctx, req)
}

func (p *kAIServiceClient) DeleteBot(ctx context.Context, req *ai.DeleteBotReq, callOptions ...callopt.Option) (r *ai.DeleteBotResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteBot(ctx, req)
}

func (p *kAIServiceClient) AddBotToGroup(ctx context.Context, req *ai.AddBotToGroupReq, callOptions ...callopt.Option) (r *ai.AddBotToGroupResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.AddBotToGroup(ctx, req)
}

func (p *kAIServiceClient) RemoveBotFromGroup(ctx context.Context, req *ai.RemoveBotFromGroupReq, callOptions ...callopt.Option) (r *ai.RemoveBotFromGroupResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.RemoveBotFromGroup(ctx, req)
}

func (p *kAIServiceClient) ListGroupBots(ctx context.Context, req *ai.ListGroupBotsReq, callOptions ...callopt.Option) (r *ai.ListGroupBotsResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListGroupBots(ctx, req)
}

func (p *kAIServiceClient) ListBotGroups(ctx context.Context, req *ai.ListBotGroupsReq, callOptions ...callopt.Option) (r *ai.ListBotGroupsResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListBotGroups(ctx, req)
}

func (p *kAIServiceClient) RegisterMCPServer(ctx context.Context, req *ai.RegisterMCPServerReq, callOptions ...callopt.Option) (r *ai.RegisterMCPServerResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.RegisterMCPServer(ctx, req)
}

func (p *kAIServiceClient) RefreshMCPServer(ctx context.Context, req *ai.RefreshMCPServerReq, callOptions ...callopt.Option) (r *ai.RefreshMCPServerResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.RefreshMCPServer(ctx, req)
}

func (p *kAIServiceClient) ListMCPServers(ctx context.Context, req *ai.ListMCPServersReq, callOptions ...callopt.Option) (r *ai.ListMCPServersResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListMCPServers(ctx, req)
}

func (p *kAIServiceClient) DeleteMCPServer(ctx context.Context, req *ai.DeleteMCPServerReq, callOptions ...callopt.Option) (r *ai.DeleteMCPServerResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteMCPServer(ctx, req)
}

func (p *kAIServiceClient) ListTools(ctx context.Context, req *ai.ListToolsReq, callOptions ...callopt.Option) (r *ai.ListToolsResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListTools(ctx, req)
}

func (p *kAIServiceClient) SaveCredential(ctx context.Context, req *ai.SaveCredentialReq, callOptions ...callopt.Option) (r *ai.SaveCredentialResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SaveCredential(ctx, req)
}

func (p *kAIServiceClient) DeleteCredential(ctx context.Context, req *ai.DeleteCredentialReq, callOptions ...callopt.Option) (r *ai.DeleteCredentialResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteCredential(ctx, req)
}

func (p *kAIServiceClient) ListCredentials(ctx context.Context, req *ai.ListCredentialsReq, callOptions ...callopt.Option) (r *ai.ListCredentialsResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListCredentials(ctx, req)
}
