// Code generated by hertz generator.

package api

import (
	"StreamCore/api/middleware"
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _authMw() []app.HandlerFunc {
	return nil
}

func _mfaMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _mfabindMw() []app.HandlerFunc {
	return []app.HandlerFunc{middleware.JWTAuthFunc()}
}

func _mfaqrcodeMw() []app.HandlerFunc {
	return []app.HandlerFunc{middleware.JWTAuthFunc()}
}

func _commentMw() []app.HandlerFunc {
	return []app.HandlerFunc{middleware.JWTAuthFunc()}
}

func _deletecommentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listcommentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _publishcommentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _followerMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listfollowersMw() []app.HandlerFunc {
	return []app.HandlerFunc{middleware.JWTAuthFunc()}
}

func _followingMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listfollowsMw() []app.HandlerFunc {
	return []app.HandlerFunc{middleware.JWTAuthFunc()}
}

func _friendsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listfriendsMw() []app.HandlerFunc {
	return []app.HandlerFunc{middleware.JWTAuthFunc()}
}

func _likeMw() []app.HandlerFunc {
	return []app.HandlerFunc{middleware.JWTAuthFunc()}
}

func _publishlikeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listlikeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _relationMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _followMw() []app.HandlerFunc {
	return []app.HandlerFunc{middleware.JWTAuthFunc()}
}

func _userMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getinfoMw() []app.HandlerFunc {
	return []app.HandlerFunc{middleware.JWTAuthFunc()}
}

func _loginMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _registerMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _avatarMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _uploadavatarMw() []app.HandlerFunc {
	return []app.HandlerFunc{middleware.JWTAuthFunc()}
}

func _videoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _feedMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listMw() []app.HandlerFunc {
	return []app.HandlerFunc{middleware.JWTAuthFunc()}
}

func _popularMw() []app.HandlerFunc {
	return []app.HandlerFunc{middleware.JWTAuthFunc()}
}

func _publishMw() []app.HandlerFunc {
	return []app.HandlerFunc{middleware.JWTAuthFunc()}
}

func _searchMw() []app.HandlerFunc {
	return []app.HandlerFunc{middleware.JWTAuthFunc()}
}

func _visitMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _chathandlerMw() []app.HandlerFunc {
	return []app.HandlerFunc{middleware.JWTAuthFunc()}
}

func _chatMw() []app.HandlerFunc {
	return []app.HandlerFunc{middleware.JWTAuthFunc()}
}

func _groupMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _applyjoingroupMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _creategroupMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _historyMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listgroupmessagesallMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listgroupmessagesMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _history0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listwhispermessagesallMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listwhispermessagesMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _whisperMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _applyMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _respondgroupapplyMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _mfaverifyMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _refreshtokenMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _aiMw() []app.HandlerFunc {
	return []app.HandlerFunc{middleware.JWTAuthFunc()}
}

func _botMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createbotMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletebotMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getbotMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _removebotfromgroupMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _addbottogroupMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatebotMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listbotsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _credentialMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _savecredentialMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletecredentialMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listcredentialsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listtoolsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _group_idMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listgroupbotsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _mcpMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _serverMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _registermcpserverMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _refreshmcpserverMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletemcpserverMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listmcpserversMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _group0Mw() []app.HandlerFunc {
	// your code...
	return nil
}
